CCTLib: tests/address_compare.cpp File Reference
address_compare.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <iostream>
#include <unistd.h>
#include <assert.h>
#include <string.h>
#include <sstream>
#include "pin.H"
#include "xed-interface.h"
#include <unordered_set>
Macros
#define MAX_FILE_PATH (1000)
Functions
INT32 Usage2 ()
void ClientInit (int argc, char *argv[])
xed_uint64_t watchpointRegisterValueCallback (xed_reg_enum_t reg, void *_ctxt, xed_bool_t *error)
VOID Checker (ADDRINT addr, ADDRINT ip, const CONTEXT *ctxt, UINT32 idx)
VOID Instruction (INS ins, VOID *v)
VOID Fini (INT32 code, VOID *v)
int main (int argc, char *argv[])
Variables
FILE * gTraceFile
xed_state_t xedState
std::unordered_set< ADDRINT > hm
Macro Definition Documentation
MAX_FILE_PATH
#define MAX_FILE_PATH (1000)
Definition at line 20 of file address_compare.cpp.
Function Documentation
Checker()
VOID Checker (ADDRINT addr, ADDRINT ip, const CONTEXT * ctxt, UINT32 idx)
Definition at line 204 of file address_compare.cpp.
References address, buf, hm, ip, and xedState.
Referenced by Instruction().
ClientInit()
void ClientInit (int argc, char * argv[])
Definition at line 36 of file address_compare.cpp.
References gTraceFile, MAX_FILE_PATH, watchpointRegisterValueCallback(), and xedState.
Referenced by main().
Fini()
VOID Fini (INT32 code, VOID * v)
Definition at line 241 of file address_compare.cpp.
Referenced by main().
Instruction()
VOID Instruction (INS ins, VOID * v)
Definition at line 229 of file address_compare.cpp.
References Checker().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 244 of file address_compare.cpp.
References ClientInit(), Fini(), Instruction(), and Usage2().
Usage2()
INT32 Usage2 ()
Definition at line 24 of file address_compare.cpp.
Referenced by main().
watchpointRegisterValueCallback()
xed_uint64_t watchpointRegisterValueCallback (xed_reg_enum_t reg, void * _ctxt, xed_bool_t * error)
Definition at line 68 of file address_compare.cpp.
Referenced by ClientInit().
Variable Documentation
gTraceFile
FILE* gTraceFile
Definition at line 31 of file address_compare.cpp.
Referenced by ClientInit().
hm
std::unordered_set<ADDRINT> hm
Definition at line 202 of file address_compare.cpp.
Referenced by Checker().
xedState
xed_state_t xedState
Definition at line 33 of file address_compare.cpp.
Referenced by Checker(), and ClientInit().