set -ex
PATH_TO_GOOGLE_SPARSE_HASH=/projects/hpc/mc29/software/sparsehash-2.0.2
PATH_TO_PIN=/projects/hpc/mc29/software/pin_rev/pin-2.12-56759-gcc.4.4.7-linux/
make SPARSEHASH_PATH=$PATH_TO_GOOGLE_SPARSE_HASH PIN_PATH=$PATH_TO_PIN clean
make SPARSEHASH_PATH=$PATH_TO_GOOGLE_SPARSE_HASH PIN_PATH=$PATH_TO_PIN 
make SPARSEHASH_PATH=$PATH_TO_GOOGLE_SPARSE_HASH PIN_PATH=$PATH_TO_PIN check
echo "*********SUCCESS***********"

