CCTLib: clients/cctlib_reader.cpp File Reference
cctlib_reader.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <iostream>
#include <unistd.h>
#include <assert.h>
#include <string.h>
#include <sstream>
#include "pin.H"
#include "cctlib.H"
Functions
static INT32 Usage ()
void ClientInit (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
FILE * gTraceFile
Function Documentation
ClientInit()
void ClientInit (int argc, char * argv[])
Definition at line 30 of file cctlib_reader.cpp.
References gTraceFile, and MAX_FILE_PATH.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 55 of file cctlib_reader.cpp.
References ClientInit(), PinCCTLib::GetFullCallingContext(), gTraceFile, PinCCTLib::PinCCTLibInitForPostmortemAnalysis(), PinCCTLib::PrintFullCallingContext(), and Usage().
Usage()
static INT32 Usage () static
Definition at line 19 of file cctlib_reader.cpp.
Referenced by main().
Variable Documentation
gTraceFile
FILE* gTraceFile
Definition at line 26 of file cctlib_reader.cpp.
Referenced by ClientInit(), and main().