CCTLib: Label Class Reference
Label Class Reference
Public Member Functions
uint8_t GetLength () const
void SetLength (uint64_t len)
void IncrementRef ()
void DecrementRef ()
Label ()
LabelSegment * GetSegmentAtIndex (int index) const
void CopyLabelSegments (const Label &label)
void LabelCreateAfterFork (const Label &label, const LabelSegment &extension)
void LabelCreateAfterJoin (const Label &label)
void LabelCreateAfterBarrier (const Label &label)
void LabelCreateAfterEneringOrderedSection (const Label &label)
void LabelCreateAfterExitingOrderedSection (const Label &label)
Label (LabelCreationType type, const Label &label, const LabelSegment &extension=defaultExtension)
void PrintLabel () const
Private Attributes
LabelSegment * m_LabelSegment
uint8_t m_labelLength
volatile atomic< uint64_t > m_refCount
Detailed Description
Definition at line 150 of file omp_datarace_client.cpp.
Constructor & Destructor Documentation
Label() [1/2]
Label::Label () inline
Definition at line 167 of file omp_datarace_client.cpp.
References LabelSegment::offset, LabelSegment::phase, and LabelSegment::span.
Label() [2/2]
Label::Label (LabelCreationType type, const Label & label, const LabelSegment & extension = defaultExtension) inline explicit
Definition at line 241 of file omp_datarace_client.cpp.
References CREATE_AFTER_BARRIER, CREATE_AFTER_ENTERING_ORDERED_SECTION, CREATE_AFTER_EXITING_ORDERED_SECTION, CREATE_AFTER_FORK, and CREATE_AFTER_JOIN.
Member Function Documentation
CopyLabelSegments()
void Label::CopyLabelSegments (const Label & label) inline
Definition at line 181 of file omp_datarace_client.cpp.
References GetLength(), and m_LabelSegment.
DecrementRef()
void Label::DecrementRef () inline
Definition at line 160 of file omp_datarace_client.cpp.
Referenced by CommitChangesToShadowMemory().
GetLength()
uint8_t Label::GetLength () const inline
Definition at line 157 of file omp_datarace_client.cpp.
Referenced by CopyLabelSegments(), LabelCreateAfterBarrier(), LabelCreateAfterEneringOrderedSection(), LabelCreateAfterExitingOrderedSection(), LabelCreateAfterFork(), LabelCreateAfterJoin(), and LabelIterator::LabelIterator().
GetSegmentAtIndex()
LabelSegment* Label::GetSegmentAtIndex (int index) const inline
Definition at line 176 of file omp_datarace_client.cpp.
Referenced by LabelIterator::NextSegment().
IncrementRef()
void Label::IncrementRef () inline
Definition at line 159 of file omp_datarace_client.cpp.
Referenced by CommitChangesToShadowMemory().
LabelCreateAfterBarrier()
void Label::LabelCreateAfterBarrier (const Label & label) inline
Definition at line 217 of file omp_datarace_client.cpp.
References GetLength(), LabelSegment::offset, and LabelSegment::span.
LabelCreateAfterEneringOrderedSection()
void Label::LabelCreateAfterEneringOrderedSection (const Label & label) inline
Definition at line 226 of file omp_datarace_client.cpp.
References GetLength(), and LabelSegment::phase.
LabelCreateAfterExitingOrderedSection()
void Label::LabelCreateAfterExitingOrderedSection (const Label & label) inline
Definition at line 234 of file omp_datarace_client.cpp.
References GetLength(), and LabelSegment::phase.
LabelCreateAfterFork()
void Label::LabelCreateAfterFork (const Label & label, const LabelSegment & extension) inline
Definition at line 190 of file omp_datarace_client.cpp.
References GetLength(), and m_LabelSegment.
LabelCreateAfterJoin()
void Label::LabelCreateAfterJoin (const Label & label) inline
Definition at line 202 of file omp_datarace_client.cpp.
References GetLength(), m_LabelSegment, LabelSegment::offset, and LabelSegment::span.
PrintLabel()
void Label::PrintLabel () const inline
Definition at line 263 of file omp_datarace_client.cpp.
References gTraceFile.
Referenced by CheckWrite(), and DumpRaceInfo().
SetLength()
void Label::SetLength (uint64_t len) inline
Definition at line 158 of file omp_datarace_client.cpp.
Member Data Documentation
m_labelLength
uint8_t Label::m_labelLength private
Definition at line 153 of file omp_datarace_client.cpp.
m_LabelSegment
LabelSegment* Label::m_LabelSegment private
Definition at line 152 of file omp_datarace_client.cpp.
Referenced by CopyLabelSegments(), LabelCreateAfterFork(), and LabelCreateAfterJoin().
m_refCount
volatile atomic<uint64_t> Label::m_refCount private
Definition at line 154 of file omp_datarace_client.cpp.
The documentation for this class was generated from the following file:
clients/omp_datarace_client.cpp