CCTLib: anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration Class Reference
anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration Class Reference
Protected Member Functions
void SetUp () override
long run_and_parse_footprint (const std::string &victim)
Protected Attributes
std::string root_
std::string tool_
Detailed Description
Definition at line 84 of file footprint_integration_test.cpp.
Member Function Documentation
run_and_parse_footprint()
long anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::run_and_parse_footprint (const std::string & victim) inline protected
Definition at line 94 of file footprint_integration_test.cpp.
References anonymous_namespace{footprint_integration_test.cpp}::cleanup(), anonymous_namespace{footprint_integration_test.cpp}::find_newest(), anonymous_namespace{footprint_integration_test.cpp}::parse_first_footprint(), anonymous_namespace{footprint_integration_test.cpp}::read_file(), and anonymous_namespace{footprint_integration_test.cpp}::run_pin().
SetUp()
void anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::SetUp () inline override protected
Definition at line 87 of file footprint_integration_test.cpp.
References anonymous_namespace{footprint_integration_test.cpp}::cctlib_root(), and anonymous_namespace{footprint_integration_test.cpp}::pin_root().
Member Data Documentation
root_
std::string anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::root_ protected
Definition at line 86 of file footprint_integration_test.cpp.
tool_
std::string anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::tool_ protected
Definition at line 86 of file footprint_integration_test.cpp.
The documentation for this class was generated from the following file:
tests/gtest/footprint_integration_test.cpp