CCTLib: anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration Class Reference
anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration Class Reference
Protected Member Functions
void SetUp () override
double run_and_parse_pct (const std::string &victim)
Protected Attributes
std::string root_
std::string tool_
Detailed Description
Definition at line 83 of file loadspy_integration_test.cpp.
Member Function Documentation
run_and_parse_pct()
double anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::run_and_parse_pct (const std::string & victim) inline protected
Definition at line 95 of file loadspy_integration_test.cpp.
References anonymous_namespace{loadspy_integration_test.cpp}::cleanup(), anonymous_namespace{loadspy_integration_test.cpp}::find_newest(), anonymous_namespace{loadspy_integration_test.cpp}::parse_first_redundant_pct(), anonymous_namespace{loadspy_integration_test.cpp}::read_file(), and anonymous_namespace{loadspy_integration_test.cpp}::run_pin().
SetUp()
void anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::SetUp () inline override protected
Definition at line 86 of file loadspy_integration_test.cpp.
References anonymous_namespace{loadspy_integration_test.cpp}::cctlib_root(), and anonymous_namespace{loadspy_integration_test.cpp}::pin_root().
Member Data Documentation
root_
std::string anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::root_ protected
Definition at line 85 of file loadspy_integration_test.cpp.
tool_
std::string anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::tool_ protected
Definition at line 85 of file loadspy_integration_test.cpp.
The documentation for this class was generated from the following file:
tests/gtest/loadspy_integration_test.cpp