CCTLib: anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration Class Reference
anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration Class Reference
Protected Member Functions
void SetUp () override
double run_and_parse_red (const std::string &victim)
Protected Attributes
std::string root_
std::string tool_
Detailed Description
Definition at line 87 of file rvn_integration_test.cpp.
Member Function Documentation
run_and_parse_red()
double anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::run_and_parse_red (const std::string & victim) inline protected
Definition at line 97 of file rvn_integration_test.cpp.
References anonymous_namespace{rvn_integration_test.cpp}::cleanup(), anonymous_namespace{rvn_integration_test.cpp}::find_newest(), anonymous_namespace{rvn_integration_test.cpp}::parse_redundancy(), anonymous_namespace{rvn_integration_test.cpp}::read_file(), and anonymous_namespace{rvn_integration_test.cpp}::run_pin().
SetUp()
void anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::SetUp () inline override protected
Definition at line 90 of file rvn_integration_test.cpp.
References anonymous_namespace{rvn_integration_test.cpp}::cctlib_root(), and anonymous_namespace{rvn_integration_test.cpp}::pin_root().
Member Data Documentation
root_
std::string anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::root_ protected
Definition at line 89 of file rvn_integration_test.cpp.
tool_
std::string anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::tool_ protected
Definition at line 89 of file rvn_integration_test.cpp.
The documentation for this class was generated from the following file:
tests/gtest/rvn_integration_test.cpp