CCTLib: anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration Class Reference
anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration Class Reference
Protected Member Functions
void SetUp () override
std::vector< double > run_and_parse (const std::string &victim)
Protected Attributes
std::string root_
std::string tool_
Detailed Description
Definition at line 95 of file ins_reuse_integration_test.cpp.
Member Function Documentation
run_and_parse()
std::vector<double> anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::run_and_parse (const std::string & victim) inline protected
Definition at line 105 of file ins_reuse_integration_test.cpp.
References anonymous_namespace{ins_reuse_integration_test.cpp}::cleanup(), anonymous_namespace{ins_reuse_integration_test.cpp}::find_newest(), anonymous_namespace{ins_reuse_integration_test.cpp}::parse_histogram(), anonymous_namespace{ins_reuse_integration_test.cpp}::read_file(), and anonymous_namespace{ins_reuse_integration_test.cpp}::run_pin().
SetUp()
void anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::SetUp () inline override protected
Definition at line 98 of file ins_reuse_integration_test.cpp.
References anonymous_namespace{ins_reuse_integration_test.cpp}::cctlib_root(), and anonymous_namespace{ins_reuse_integration_test.cpp}::pin_root().
Member Data Documentation
root_
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::root_ protected
Definition at line 97 of file ins_reuse_integration_test.cpp.
tool_
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::tool_ protected
Definition at line 97 of file ins_reuse_integration_test.cpp.
The documentation for this class was generated from the following file:
tests/gtest/ins_reuse_integration_test.cpp