CCTLib: LabelIterator Class Reference
LabelIterator Class Reference
Public Member Functions
LabelIterator (const Label &label)
LabelSegment * NextSegment ()
Private Attributes
const Label & m_label
uint8_t m_curLoc
uint8_t m_len
Detailed Description
Definition at line 271 of file omp_datarace_client.cpp.
Constructor & Destructor Documentation
LabelIterator()
LabelIterator::LabelIterator (const Label & label) inline
Definition at line 278 of file omp_datarace_client.cpp.
References Label::GetLength().
Member Function Documentation
NextSegment()
LabelSegment* LabelIterator::NextSegment () inline
Definition at line 284 of file omp_datarace_client.cpp.
References Label::GetSegmentAtIndex().
Referenced by HappensBefore(), IsLeftOf(), and MaximizesExitRank().
Member Data Documentation
m_curLoc
uint8_t LabelIterator::m_curLoc private
Definition at line 274 of file omp_datarace_client.cpp.
m_label
const Label& LabelIterator::m_label private
Definition at line 273 of file omp_datarace_client.cpp.
m_len
uint8_t LabelIterator::m_len private
Definition at line 275 of file omp_datarace_client.cpp.
The documentation for this class was generated from the following file:
clients/omp_datarace_client.cpp