var dir_188a8b06331a0186d7b5536d2b5a1b80 =
[
    [ "deadspy_addressing_tp.c", "deadspy__addressing__tp_8c.html", "deadspy__addressing__tp_8c" ],
    [ "deadspy_avx32_tp.c", "deadspy__avx32__tp_8c.html", "deadspy__avx32__tp_8c" ],
    [ "deadspy_cmpxchg_tn.c", "deadspy__cmpxchg__tn_8c.html", "deadspy__cmpxchg__tn_8c" ],
    [ "deadspy_cross_page_qword_tp.c", "deadspy__cross__page__qword__tp_8c.html", "deadspy__cross__page__qword__tp_8c" ],
    [ "deadspy_movnti_tp.c", "deadspy__movnti__tp_8c.html", "deadspy__movnti__tp_8c" ],
    [ "deadspy_partial_qword_then_byte_high_tp.c", "deadspy__partial__qword__then__byte__high__tp_8c.html", "deadspy__partial__qword__then__byte__high__tp_8c" ],
    [ "deadspy_partial_qword_then_byte_tp.c", "deadspy__partial__qword__then__byte__tp_8c.html", "deadspy__partial__qword__then__byte__tp_8c" ],
    [ "deadspy_prefetch_tp.c", "deadspy__prefetch__tp_8c.html", "deadspy__prefetch__tp_8c" ],
    [ "deadspy_pushpop_dead_tp.c", "deadspy__pushpop__dead__tp_8c.html", "deadspy__pushpop__dead__tp_8c" ],
    [ "deadspy_repstos_tp.c", "deadspy__repstos__tp_8c.html", "deadspy__repstos__tp_8c" ],
    [ "deadspy_sse16_tp.c", "deadspy__sse16__tp_8c.html", "deadspy__sse16__tp_8c" ],
    [ "deadspy_xchg_tn.c", "deadspy__xchg__tn_8c.html", "deadspy__xchg__tn_8c" ],
    [ "footprint_avx32_sweep.c", "footprint__avx32__sweep_8c.html", "footprint__avx32__sweep_8c" ],
    [ "ins_reuse_simd_loop.c", "ins__reuse__simd__loop_8c.html", "ins__reuse__simd__loop_8c" ],
    [ "loadspy_avx32_tp.c", "loadspy__avx32__tp_8c.html", "loadspy__avx32__tp_8c" ],
    [ "loadspy_cross_page_tp.c", "loadspy__cross__page__tp_8c.html", "loadspy__cross__page__tp_8c" ],
    [ "loadspy_mixed_widths_tp.c", "loadspy__mixed__widths__tp_8c.html", "loadspy__mixed__widths__tp_8c" ],
    [ "loadspy_repmovs_tp.c", "loadspy__repmovs__tp_8c.html", "loadspy__repmovs__tp_8c" ],
    [ "loadspy_sse16_tp.c", "loadspy__sse16__tp_8c.html", "loadspy__sse16__tp_8c" ],
    [ "redspy_avx32_tp.c", "redspy__avx32__tp_8c.html", "redspy__avx32__tp_8c" ],
    [ "redspy_cross_page_tp.c", "redspy__cross__page__tp_8c.html", "redspy__cross__page__tp_8c" ],
    [ "redspy_immediate_tp.c", "redspy__immediate__tp_8c.html", "redspy__immediate__tp_8c" ],
    [ "redspy_partial_qword_then_byte_tp.c", "redspy__partial__qword__then__byte__tp_8c.html", "redspy__partial__qword__then__byte__tp_8c" ],
    [ "redspy_scalar_sse_tp.c", "redspy__scalar__sse__tp_8c.html", "redspy__scalar__sse__tp_8c" ],
    [ "redspy_sse16_tp.c", "redspy__sse16__tp_8c.html", "redspy__sse16__tp_8c" ],
    [ "redspy_zero_fill_tp.c", "redspy__zero__fill__tp_8c.html", "redspy__zero__fill__tp_8c" ],
    [ "rvn_repeated_add.c", "rvn__repeated__add_8c.html", "rvn__repeated__add_8c" ]
];