CCTLib: tests/gtest/apps/exceptions/exc_simple_throw.cpp File Reference
exc_simple_throw.cpp File Reference
#include <cstdint>
#include <cstdio>
Macros
#define N 5000
Functions
__attribute__ ((noinline)) void simple_try_marker(int i)
static void inner (int i)
static void middle (int i)
static void outer (int i)
int main (int argc, char **argv)
Variables
static volatile uint64_t sink
static uint64_t buf [N]
Macro Definition Documentation
N
#define N 5000
Definition at line 10 of file exc_simple_throw.cpp.
Function Documentation
__attribute__()
__attribute__ ((noinline))
Definition at line 14 of file exc_simple_throw.cpp.
References sink.
inner()
static void inner (int i) static
Definition at line 23 of file exc_simple_throw.cpp.
References buf.
Referenced by middle().
main()
int main (int argc, char ** argv)
Definition at line 30 of file exc_simple_throw.cpp.
References buf, N, outer(), and sink.
middle()
static void middle (int i) static
Definition at line 27 of file exc_simple_throw.cpp.
References buf, and inner().
Referenced by outer().
outer()
static void outer (int i) static
Definition at line 28 of file exc_simple_throw.cpp.
References buf, and middle().
Referenced by main().
Variable Documentation
buf
uint64_t buf[N] static
Definition at line 12 of file exc_simple_throw.cpp.
Referenced by inner(), main(), middle(), and outer().
sink
volatile uint64_t sink static
Definition at line 11 of file exc_simple_throw.cpp.
Referenced by __attribute__(), and main().