CCTLib: tests/gtest/apps/exceptions/exc_catch_and_resume.cpp File Reference
exc_catch_and_resume.cpp File Reference
#include <cstdint>
#include <cstdio>
Macros
#define ITERS 2000
Functions
__attribute__ ((noinline)) void resume_try_marker(int i)
static void may_throw (int i)
static void resume_after_catch (int i)
static void post_catch_worker (int i)
int main (int argc, char **argv)
Variables
static volatile uint64_t sink
static uint64_t pre_marker [ITERS]
static uint64_t catch_marker [ITERS]
static uint64_t post_marker [ITERS]
Macro Definition Documentation
ITERS
#define ITERS 2000
Definition at line 19 of file exc_catch_and_resume.cpp.
Function Documentation
__attribute__()
__attribute__ ((noinline))
Definition at line 25 of file exc_catch_and_resume.cpp.
References sink.
main()
int main (int argc, char ** argv)
Definition at line 57 of file exc_catch_and_resume.cpp.
References catch_marker, ITERS, post_catch_worker(), post_marker, pre_marker, resume_after_catch(), and sink.
may_throw()
static void may_throw (int i) static
Definition at line 32 of file exc_catch_and_resume.cpp.
References pre_marker.
Referenced by resume_after_catch().
post_catch_worker()
static void post_catch_worker (int i) static
Definition at line 53 of file exc_catch_and_resume.cpp.
References post_marker.
Referenced by main().
resume_after_catch()
static void resume_after_catch (int i) static
Definition at line 39 of file exc_catch_and_resume.cpp.
References catch_marker, and may_throw().
Referenced by main().
Variable Documentation
catch_marker
uint64_t catch_marker[ITERS] static
Definition at line 22 of file exc_catch_and_resume.cpp.
Referenced by main(), and resume_after_catch().
post_marker
uint64_t post_marker[ITERS] static
Definition at line 23 of file exc_catch_and_resume.cpp.
Referenced by main(), and post_catch_worker().
pre_marker
uint64_t pre_marker[ITERS] static
Definition at line 21 of file exc_catch_and_resume.cpp.
Referenced by main(), and may_throw().
sink
volatile uint64_t sink static
Definition at line 20 of file exc_catch_and_resume.cpp.
Referenced by __attribute__(), and main().