CCTLib: clients/footprint_test/test2.c File Reference
test2.c File Reference
#include <stdio.h>
#include <omp.h>
Macros
#define N (10000000)
Functions
void g ()
void h ()
void f ()
int main ()
Variables
int A [N]
int B [N/2]
Macro Definition Documentation
N
#define N (10000000)
Definition at line 4 of file test2.c.
Function Documentation
f()
void f ()
Definition at line 21 of file test2.c.
References g().
Referenced by devide(), and main().
g()
void g ()
Definition at line 9 of file test2.c.
References N.
Referenced by devide(), and f().
h()
void h ()
Definition at line 15 of file test2.c.
References N.
Referenced by devide(), and main().
main()
int main ()
Definition at line 26 of file test2.c.
References f(), and h().
Variable Documentation
A
int A[N]
Definition at line 6 of file test2.c.
B
int B[N/2]
Definition at line 7 of file test2.c.