var hierarchy =
[
    [ "A", "structA.html", null ],
    [ "AddrValPair", "structAddrValPair.html", null ],
    [ "AnalyzedMetric_t", "structAnalyzedMetric__t.html", null ],
    [ "ApproxGeneralRegisters< T, isAlias >", "structApproxGeneralRegisters.html", null ],
    [ "ApproxLargeRegisters< T, simdType >", "structApproxLargeRegisters.html", null ],
    [ "ApproxRedLogs", "structApproxRedLogs.html", null ],
    [ "ApproxRedundacyData", "structApproxRedundacyData.html", null ],
    [ "ArrayAnalysis< T, isApprox >", "structArrayAnalysis.html", null ],
    [ "AssertionRecorder", "structAssertionRecorder.html", null ],
    [ "B", "structB.html", null ],
    [ "Cache_t", "structCache__t.html", null ],
    [ "PinCCTLib::CCT_LIB_GLOBAL_STATE", "structPinCCTLib_1_1CCT__LIB__GLOBAL__STATE.html", null ],
    [ "CctInventory", "structCctInventory.html", null ],
    [ "ConcurrentShadowMemory< Ts >", "classConcurrentShadowMemory.html", null ],
    [ "DataObj", "structDataObj.html", null ],
    [ "DeadInfo", "structDeadInfo.html", null ],
    [ "DeadInfoForPresentation", "structDeadInfoForPresentation.html", null ],
    [ "DeadSpyThreadData", "structDeadSpyThreadData.html", null ],
    [ "Deep", "structDeep.html", null ],
    [ "anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis", "structanonymous__namespace_02splay__deserialize__test_8cpp_03_1_1Diagnosis.html", null ],
    [ "double_cast", "uniondouble__cast.html", null ],
    [ "DRedData", "structDRedData.html", null ],
    [ "std::exception", null, [
      [ "Base", "structBase.html", [
        [ "Mid", "structMid.html", [
          [ "Leaf", "structLeaf.html", null ]
        ] ]
      ] ]
    ] ],
    [ "PinCCTLib::fileid", "structPinCCTLib_1_1fileid.html", null ],
    [ "float_cast", "unionfloat__cast.html", null ],
    [ "Guard", "structGuard.html", null ],
    [ "HandleAliasRegisters< T, aliasGroup >", "structHandleAliasRegisters.html", null ],
    [ "HandleGeneralRegisters< T, len >", "structHandleGeneralRegisters.html", null ],
    [ "HandleSpecialRegisters< lenInt64 >", "structHandleSpecialRegisters.html", null ],
    [ "InsReuseThreadData", "structInsReuseThreadData.html", null ],
    [ "PinCCTLib::IPNode", "structPinCCTLib_1_1IPNode.html", null ],
    [ "anonymous_namespace{deadspy_integration_test.cpp}::IsaVictim", "structanonymous__namespace_02deadspy__integration__test_8cpp_03_1_1IsaVictim.html", null ],
    [ "Label", "classLabel.html", null ],
    [ "LabelIterator", "classLabelIterator.html", null ],
    [ "LabelSegment", "structLabelSegment.html", null ],
    [ "LargeReg", "structLargeReg.html", null ],
    [ "LoadSpyInstrument", "structLoadSpyInstrument.html", null ],
    [ "MemAnalysis< AccessLen >", "structMemAnalysis.html", null ],
    [ "MergedDeadInfo", "structMergedDeadInfo.html", null ],
    [ "MergedRedundantInfo", "structMergedRedundantInfo.html", null ],
    [ "PinCCTLib::ModuleInfo", "structPinCCTLib_1_1ModuleInfo.html", null ],
    [ "PinCCTLib::NewIPNode", "structPinCCTLib_1_1NewIPNode.html", null ],
    [ "node_metric_t", "structnode__metric__t.html", null ],
    [ "anonymous_namespace{rbtree_test.cpp}::NodeArena", "classanonymous__namespace_02rbtree__test_8cpp_03_1_1NodeArena.html", null ],
    [ "PinCCTLib::NormalizedIP", "structPinCCTLib_1_1NormalizedIP.html", null ],
    [ "ObjRedundancy", "structObjRedundancy.html", null ],
    [ "Pod", "structPod.html", null ],
    [ "RawMetric_t", "structRawMetric__t.html", null ],
    [ "RBTree< K, V, S >", "classRBTree.html", null ],
    [ "RBTree< uint64_t, uint32_t, uint64_t >", "classRBTree.html", null ],
    [ "RedLogs", "structRedLogs.html", null ],
    [ "RedSpyAnalysis< AccessLen, bufferOffset >", "structRedSpyAnalysis.html", null ],
    [ "RedSpyInstrument< readBufferSlotIndex >", "structRedSpyInstrument.html", null ],
    [ "anonymous_namespace{redspy_integration_test.cpp}::RedspyIsaVictim", "structanonymous__namespace_02redspy__integration__test_8cpp_03_1_1RedspyIsaVictim.html", null ],
    [ "RedSpyThreadData", "structRedSpyThreadData.html", null ],
    [ "RedundacyData", "structRedundacyData.html", null ],
    [ "RedundantInfoForPresentation", "structRedundantInfoForPresentation.html", null ],
    [ "PinCCTLib::RtnInfo", "structPinCCTLib_1_1RtnInfo.html", null ],
    [ "PinCCTLib::SerializedTraceNode", "structPinCCTLib_1_1SerializedTraceNode.html", null ],
    [ "ShadowMemory< Ts >", "classShadowMemory.html", null ],
    [ "ShadowMemory< uint64_t >", "classShadowMemory.html", null ],
    [ "sort_format_t", "structsort__format__t.html", null ],
    [ "Stats_t", "structStats__t.html", null ],
    [ "TData", "structTData.html", null ],
    [ "testing::Test", null, [
      [ "anonymous_namespace{cache_client_integration_test.cpp}::CacheClientIntegration", "classanonymous__namespace_02cache__client__integration__test_8cpp_03_1_1CacheClientIntegration.html", null ],
      [ "anonymous_namespace{cctlib_integration_test.cpp}::CCTLibIntegration", "classanonymous__namespace_02cctlib__integration__test_8cpp_03_1_1CCTLibIntegration.html", null ],
      [ "anonymous_namespace{deadspy_integration_test.cpp}::DeadspyIntegration", "classanonymous__namespace_02deadspy__integration__test_8cpp_03_1_1DeadspyIntegration.html", [
        [ "anonymous_namespace{deadspy_integration_test.cpp}::DeadspyIsa", "classanonymous__namespace_02deadspy__integration__test_8cpp_03_1_1DeadspyIsa.html", null ]
      ] ],
      [ "anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration", "classanonymous__namespace_02footprint__integration__test_8cpp_03_1_1FootprintIntegration.html", null ],
      [ "anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration", "classanonymous__namespace_02ins__reuse__integration__test_8cpp_03_1_1InsReuseIntegration.html", null ],
      [ "anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration", "classanonymous__namespace_02loadspy__integration__test_8cpp_03_1_1LoadspyIntegration.html", [
        [ "anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIsa", "classanonymous__namespace_02loadspy__integration__test_8cpp_03_1_1LoadspyIsa.html", null ]
      ] ],
      [ "anonymous_namespace{omp_race_integration_test.cpp}::OmpRaceIntegration", "classanonymous__namespace_02omp__race__integration__test_8cpp_03_1_1OmpRaceIntegration.html", null ],
      [ "anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration", "classanonymous__namespace_02redspy__integration__test_8cpp_03_1_1RedspyIntegration.html", [
        [ "anonymous_namespace{redspy_integration_test.cpp}::RedspyIsa", "classanonymous__namespace_02redspy__integration__test_8cpp_03_1_1RedspyIsa.html", null ]
      ] ],
      [ "anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration", "classanonymous__namespace_02rvn__integration__test_8cpp_03_1_1RVNIntegration.html", null ]
    ] ],
    [ "testing::TestWithParam", null, [
      [ "anonymous_namespace{exception_integration_test.cpp}::ExceptionRun", "classanonymous__namespace_02exception__integration__test_8cpp_03_1_1ExceptionRun.html", null ],
      [ "anonymous_namespace{exception_shape_test.cpp}::ExceptionShape", "classanonymous__namespace_02exception__shape__test_8cpp_03_1_1ExceptionShape.html", null ],
      [ "anonymous_namespace{recursion_integration_test.cpp}::RecursionShape", "classanonymous__namespace_02recursion__integration__test_8cpp_03_1_1RecursionShape.html", null ],
      [ "anonymous_namespace{splay_deserialize_test.cpp}::SplayDeserialize", "classanonymous__namespace_02splay__deserialize__test_8cpp_03_1_1SplayDeserialize.html", null ]
    ] ],
    [ "PinCCTLib::ThreadData", "structPinCCTLib_1_1ThreadData.html", null ],
    [ "ThreadData_t", "classThreadData__t.html", null ],
    [ "anonymous_namespace{exception_integration_test.cpp}::ToolSpec", "structanonymous__namespace_02exception__integration__test_8cpp_03_1_1ToolSpec.html", null ],
    [ "PinCCTLib::TraceNode", "structPinCCTLib_1_1TraceNode.html", null ],
    [ "anonymous_namespace{splay_deserialize_test.cpp}::TraceSplay", "structanonymous__namespace_02splay__deserialize__test_8cpp_03_1_1TraceSplay.html", null ],
    [ "PinCCTLib::TraceSplay", "structPinCCTLib_1_1TraceSplay.html", null ],
    [ "TraceSplay", "structTraceSplay.html", null ],
    [ "TreeNode< K, V, S >", "structTreeNode.html", null ],
    [ "UnrolledConjunction< start, end, incr >", "structUnrolledConjunction.html", null ],
    [ "UnrolledConjunction< end, end, incr >", "structUnrolledConjunction_3_01end_00_01end_00_01incr_01_4.html", null ],
    [ "UnrolledConjunctionApprox< start, end, incr >", "structUnrolledConjunctionApprox.html", null ],
    [ "UnrolledConjunctionApprox< end, end, incr >", "structUnrolledConjunctionApprox_3_01end_00_01end_00_01incr_01_4.html", null ],
    [ "UnrolledCount< start, end, step >", "structUnrolledCount.html", null ],
    [ "UnrolledCount< end, end, step >", "structUnrolledCount_3_01end_00_01end_00_01step_01_4.html", null ],
    [ "UnrolledCountApprox< start, end, step >", "structUnrolledCountApprox.html", null ],
    [ "UnrolledCountApprox< end, end, step >", "structUnrolledCountApprox_3_01end_00_01end_00_01step_01_4.html", null ],
    [ "UnrolledLoop< start, end, incr >", "structUnrolledLoop.html", null ],
    [ "UnrolledLoop< end, end, incr >", "structUnrolledLoop_3_01end_00_01end_00_01incr_01_4.html", null ],
    [ "UnrolledLoop< end, end, incr, conditional, approx >", "structUnrolledLoop_3_01end_00_01end_00_01incr_00_01conditional_00_01approx_01_4.html", null ],
    [ "anonymous_namespace{exception_integration_test.cpp}::VictimSpec", "structanonymous__namespace_02exception__integration__test_8cpp_03_1_1VictimSpec.html", null ],
    [ "anonymous_namespace{exception_shape_test.cpp}::VictimSpec", "structanonymous__namespace_02exception__shape__test_8cpp_03_1_1VictimSpec.html", null ],
    [ "anonymous_namespace{recursion_integration_test.cpp}::VictimSpec", "structanonymous__namespace_02recursion__integration__test_8cpp_03_1_1VictimSpec.html", null ],
    [ "Virt", "structVirt.html", null ],
    [ "testing::WithParamInterface", null, [
      [ "anonymous_namespace{deadspy_integration_test.cpp}::DeadspyIsa", "classanonymous__namespace_02deadspy__integration__test_8cpp_03_1_1DeadspyIsa.html", null ],
      [ "anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIsa", "classanonymous__namespace_02loadspy__integration__test_8cpp_03_1_1LoadspyIsa.html", null ],
      [ "anonymous_namespace{redspy_integration_test.cpp}::RedspyIsa", "classanonymous__namespace_02redspy__integration__test_8cpp_03_1_1RedspyIsa.html", null ]
    ] ],
    [ "Wrap", "structWrap.html", null ],
    [ "ZeroSpyAnalysis< T, AccessLen, isApprox >", "structZeroSpyAnalysis.html", null ]
];