CCTLib: anonymous_namespace{exception_shape_test.cpp} Namespace Reference
anonymous_namespace{exception_shape_test.cpp} Namespace Reference
Classes
struct VictimSpec
class ExceptionShape
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin_capture (const std::string &tool, const std::vector< std::string > &toolArgs, const std::string &victim, std::string *stderrOut)
TEST_P (ExceptionShape, CctShapeSurvivesUnwind)
INSTANTIATE_TEST_SUITE_P (Victims, ExceptionShape, ::testing::ValuesIn(kVictims), [](const testing::TestParamInfo< ExceptionShape::ParamType > &info) { return std::string(info.param.name);})
Variables
const VictimSpec kVictims []
Function Documentation
cctlib_root()
std::string anonymous_namespace{exception_shape_test.cpp}::cctlib_root ()
Definition at line 38 of file exception_shape_test.cpp.
References env().
Referenced by anonymous_namespace{exception_shape_test.cpp}::ExceptionShape::SetUp().
env()
std::string anonymous_namespace{exception_shape_test.cpp}::env (const char * n)
Definition at line 37 of file exception_shape_test.cpp.
Referenced by cctlib_root(), pin_root(), and TEST_P().
INSTANTIATE_TEST_SUITE_P()
anonymous_namespace{exception_shape_test.cpp}::INSTANTIATE_TEST_SUITE_P (Victims , ExceptionShape , ::testing::ValuesIn(kVictims) , [] (const testing::TestParamInfo< ExceptionShape::ParamType > &info) { return std::string(info.param.name);})
pin_root()
std::string anonymous_namespace{exception_shape_test.cpp}::pin_root ()
Definition at line 42 of file exception_shape_test.cpp.
References env().
Referenced by run_pin_capture(), and anonymous_namespace{exception_shape_test.cpp}::ExceptionShape::SetUp().
run_pin_capture()
int anonymous_namespace{exception_shape_test.cpp}::run_pin_capture (const std::string & tool, const std::vector< std::string > & toolArgs, const std::string & victim, std::string * stderrOut)
Definition at line 44 of file exception_shape_test.cpp.
References a, buf, pin_root(), and PinCCTLib::status.
Referenced by TEST_P().
TEST_P()
anonymous_namespace{exception_shape_test.cpp}::TEST_P (ExceptionShape , CctShapeSurvivesUnwind)
Definition at line 134 of file exception_shape_test.cpp.
References env(), and run_pin_capture().
Variable Documentation
kVictims
const VictimSpec anonymous_namespace{exception_shape_test.cpp}::kVictims[]
Initial value:
= {
    { "exc_simple_throw",     true  },
    { "exc_deep_unwind",      false },
    { "exc_rethrow",          true  },
    { "exc_catchall",         false },
    { "exc_dtor_cleanup",     false },
    { "exc_stress_loop",      true  },
    { "exc_polymorphic",      false },
    { "exc_recurse_trycatch", false },
    { "exc_none_tn",          true  },
    { "exc_uncaught_tn",      false },
    { "exc_ctor_throw",       false },
    { "exc_catch_and_resume", false },
    { "sig_longjmp",          false },
    { "sig_sigsegv_recover",  false },
}
Definition at line 107 of file exception_shape_test.cpp.