CCTLib: anonymous_namespace{loadspy_integration_test.cpp} Namespace Reference
anonymous_namespace{loadspy_integration_test.cpp} Namespace Reference
Classes
class LoadspyIntegration
class LoadspyIsa
Functions
std::string env (const char *name)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
std::string find_newest (const std::string &dir, const std::string &prefix)
std::string read_file (const std::string &path)
void cleanup (const std::string &dir, const std::string &prefix)
double parse_first_redundant_pct (const std::string &content)
TEST_F (LoadspyIntegration, RunsCleanlyOnLs)
TEST_F (LoadspyIntegration, TruePositiveHigherThanTrueNegative)
TEST_F (LoadspyIntegration, TPReportAttributesToLoad8)
TEST_P (LoadspyIsa, ExceedsBaseline)
TEST_P (LoadspyIsa, AttributionInReport)
INSTANTIATE_TEST_SUITE_P (IsaBreadth, LoadspyIsa, ::testing::Values("loadspy_sse16_tp", "loadspy_avx32_tp", "loadspy_repmovs_tp", "loadspy_cross_page_tp", "loadspy_mixed_widths_tp"), [](const testing::TestParamInfo< const char * > &info) { return std::string(info.param);})
Function Documentation
cctlib_root()
std::string anonymous_namespace{loadspy_integration_test.cpp}::cctlib_root ()
Definition at line 30 of file loadspy_integration_test.cpp.
References env().
Referenced by anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::SetUp().
cleanup()
void anonymous_namespace{loadspy_integration_test.cpp}::cleanup (const std::string & dir, const std::string & prefix)
Definition at line 72 of file loadspy_integration_test.cpp.
Referenced by anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::run_and_parse_pct(), TEST_F(), and TEST_P().
env()
std::string anonymous_namespace{loadspy_integration_test.cpp}::env (const char * name)
Definition at line 29 of file loadspy_integration_test.cpp.
Referenced by cctlib_root(), pin_root(), and run_pin().
find_newest()
std::string anonymous_namespace{loadspy_integration_test.cpp}::find_newest (const std::string & dir, const std::string & prefix)
Definition at line 59 of file loadspy_integration_test.cpp.
References buf.
Referenced by anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::run_and_parse_pct(), TEST_F(), and TEST_P().
INSTANTIATE_TEST_SUITE_P()
anonymous_namespace{loadspy_integration_test.cpp}::INSTANTIATE_TEST_SUITE_P (IsaBreadth , LoadspyIsa , ::testing::Values("loadspy_sse16_tp", "loadspy_avx32_tp", "loadspy_repmovs_tp", "loadspy_cross_page_tp", "loadspy_mixed_widths_tp") , [] (const testing::TestParamInfo< const char * > &info) { return std::string(info.param);})
parse_first_redundant_pct()
double anonymous_namespace{loadspy_integration_test.cpp}::parse_first_redundant_pct (const std::string & content)
Definition at line 76 of file loadspy_integration_test.cpp.
Referenced by anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::run_and_parse_pct().
pin_root()
std::string anonymous_namespace{loadspy_integration_test.cpp}::pin_root ()
Definition at line 31 of file loadspy_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::SetUp().
read_file()
std::string anonymous_namespace{loadspy_integration_test.cpp}::read_file (const std::string & path)
Definition at line 69 of file loadspy_integration_test.cpp.
Referenced by anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::run_and_parse_pct().
run_pin()
int anonymous_namespace{loadspy_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 33 of file loadspy_integration_test.cpp.
References a, env(), pin_root(), and PinCCTLib::status.
Referenced by anonymous_namespace{loadspy_integration_test.cpp}::LoadspyIntegration::run_and_parse_pct(), TEST_F(), and TEST_P().
TEST_F() [1/3]
anonymous_namespace{loadspy_integration_test.cpp}::TEST_F (LoadspyIntegration , RunsCleanlyOnLs)
Definition at line 105 of file loadspy_integration_test.cpp.
TEST_F() [2/3]
anonymous_namespace{loadspy_integration_test.cpp}::TEST_F (LoadspyIntegration , TPReportAttributesToLoad8)
Definition at line 131 of file loadspy_integration_test.cpp.
References buf, cleanup(), find_newest(), and run_pin().
TEST_F() [3/3]
anonymous_namespace{loadspy_integration_test.cpp}::TEST_F (LoadspyIntegration , TruePositiveHigherThanTrueNegative)
Definition at line 120 of file loadspy_integration_test.cpp.
TEST_P() [1/2]
anonymous_namespace{loadspy_integration_test.cpp}::TEST_P (LoadspyIsa , AttributionInReport)
Definition at line 169 of file loadspy_integration_test.cpp.
References buf, cleanup(), find_newest(), and run_pin().
TEST_P() [2/2]
anonymous_namespace{loadspy_integration_test.cpp}::TEST_P (LoadspyIsa , ExceedsBaseline)
Definition at line 159 of file loadspy_integration_test.cpp.