CCTLib: anonymous_namespace{omp_race_integration_test.cpp} Namespace Reference
anonymous_namespace{omp_race_integration_test.cpp} Namespace Reference
Classes
class OmpRaceIntegration
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
TEST_F (OmpRaceIntegration, RunsCleanlyOnLs)
TEST_F (OmpRaceIntegration, RunsOnRaceVictim)
TEST_F (OmpRaceIntegration, RunsOnCriticalVictim)
TEST_F (OmpRaceIntegration, DISABLED_TruePositiveReportsRace)
TEST_F (OmpRaceIntegration, DISABLED_TrueNegativeReportsNoRace)
Function Documentation
cctlib_root()
std::string anonymous_namespace{omp_race_integration_test.cpp}::cctlib_root ()
Definition at line 25 of file omp_race_integration_test.cpp.
References env().
Referenced by anonymous_namespace{omp_race_integration_test.cpp}::OmpRaceIntegration::SetUp().
env()
std::string anonymous_namespace{omp_race_integration_test.cpp}::env (const char * n)
Definition at line 24 of file omp_race_integration_test.cpp.
Referenced by cctlib_root(), and pin_root().
pin_root()
std::string anonymous_namespace{omp_race_integration_test.cpp}::pin_root ()
Definition at line 26 of file omp_race_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{omp_race_integration_test.cpp}::OmpRaceIntegration::SetUp().
run_pin()
int anonymous_namespace{omp_race_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 28 of file omp_race_integration_test.cpp.
References a, pin_root(), and PinCCTLib::status.
Referenced by TEST_F().
TEST_F() [1/5]
anonymous_namespace{omp_race_integration_test.cpp}::TEST_F (OmpRaceIntegration , DISABLED_TrueNegativeReportsNoRace)
Definition at line 87 of file omp_race_integration_test.cpp.
TEST_F() [2/5]
anonymous_namespace{omp_race_integration_test.cpp}::TEST_F (OmpRaceIntegration , DISABLED_TruePositiveReportsRace)
Definition at line 84 of file omp_race_integration_test.cpp.
TEST_F() [3/5]
anonymous_namespace{omp_race_integration_test.cpp}::TEST_F (OmpRaceIntegration , RunsCleanlyOnLs)
Definition at line 66 of file omp_race_integration_test.cpp.
References run_pin().
TEST_F() [4/5]
anonymous_namespace{omp_race_integration_test.cpp}::TEST_F (OmpRaceIntegration , RunsOnCriticalVictim)
Definition at line 78 of file omp_race_integration_test.cpp.
References run_pin().
TEST_F() [5/5]
anonymous_namespace{omp_race_integration_test.cpp}::TEST_F (OmpRaceIntegration , RunsOnRaceVictim)
Definition at line 73 of file omp_race_integration_test.cpp.
References run_pin().