CCTLib: anonymous_namespace{cache_client_integration_test.cpp} Namespace Reference
anonymous_namespace{cache_client_integration_test.cpp} Namespace Reference
Classes
class CacheClientIntegration
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
TEST_F (CacheClientIntegration, CrashesOnTrivialInputDocumentsBug)
TEST_F (CacheClientIntegration, DISABLED_SilentCachelineWriteDetected)
TEST_F (CacheClientIntegration, DISABLED_DifferingCachelineWriteNotSilent)
Function Documentation
cctlib_root()
std::string anonymous_namespace{cache_client_integration_test.cpp}::cctlib_root ()
Definition at line 40 of file cache_client_integration_test.cpp.
References env().
Referenced by anonymous_namespace{cache_client_integration_test.cpp}::CacheClientIntegration::SetUp().
env()
std::string anonymous_namespace{cache_client_integration_test.cpp}::env (const char * n)
Definition at line 39 of file cache_client_integration_test.cpp.
Referenced by cctlib_root(), and pin_root().
pin_root()
std::string anonymous_namespace{cache_client_integration_test.cpp}::pin_root ()
Definition at line 41 of file cache_client_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{cache_client_integration_test.cpp}::CacheClientIntegration::SetUp().
run_pin()
int anonymous_namespace{cache_client_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 43 of file cache_client_integration_test.cpp.
References a, pin_root(), and PinCCTLib::status.
Referenced by TEST_F().
TEST_F() [1/3]
anonymous_namespace{cache_client_integration_test.cpp}::TEST_F (CacheClientIntegration , CrashesOnTrivialInputDocumentsBug)
Definition at line 82 of file cache_client_integration_test.cpp.
References run_pin().
TEST_F() [2/3]
anonymous_namespace{cache_client_integration_test.cpp}::TEST_F (CacheClientIntegration , DISABLED_DifferingCachelineWriteNotSilent)
Definition at line 109 of file cache_client_integration_test.cpp.
TEST_F() [3/3]
anonymous_namespace{cache_client_integration_test.cpp}::TEST_F (CacheClientIntegration , DISABLED_SilentCachelineWriteDetected)
Definition at line 100 of file cache_client_integration_test.cpp.