CCTLib: anonymous_namespace{footprint_integration_test.cpp} Namespace Reference
anonymous_namespace{footprint_integration_test.cpp} Namespace Reference
Classes
class FootprintIntegration
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
std::string find_newest (const std::string &dir, const std::string &prefix)
std::string read_file (const std::string &path)
void cleanup (const std::string &dir, const std::string &prefix)
long parse_first_footprint (const std::string &content)
TEST_F (FootprintIntegration, RunsCleanlyOnLs)
TEST_F (FootprintIntegration, LargeFootprintExceedsSmall)
TEST_F (FootprintIntegration, AVX32SweepFootprintExceedsSmall)
Function Documentation
cctlib_root()
std::string anonymous_namespace{footprint_integration_test.cpp}::cctlib_root ()
Definition at line 30 of file footprint_integration_test.cpp.
References env().
Referenced by anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::SetUp().
cleanup()
void anonymous_namespace{footprint_integration_test.cpp}::cleanup (const std::string & dir, const std::string & prefix)
Definition at line 71 of file footprint_integration_test.cpp.
Referenced by anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::run_and_parse_footprint().
env()
std::string anonymous_namespace{footprint_integration_test.cpp}::env (const char * n)
Definition at line 29 of file footprint_integration_test.cpp.
Referenced by cctlib_root(), pin_root(), and run_pin().
find_newest()
std::string anonymous_namespace{footprint_integration_test.cpp}::find_newest (const std::string & dir, const std::string & prefix)
Definition at line 58 of file footprint_integration_test.cpp.
References buf.
Referenced by anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::run_and_parse_footprint().
parse_first_footprint()
long anonymous_namespace{footprint_integration_test.cpp}::parse_first_footprint (const std::string & content)
Definition at line 77 of file footprint_integration_test.cpp.
Referenced by anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::run_and_parse_footprint().
pin_root()
std::string anonymous_namespace{footprint_integration_test.cpp}::pin_root ()
Definition at line 31 of file footprint_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::SetUp().
read_file()
std::string anonymous_namespace{footprint_integration_test.cpp}::read_file (const std::string & path)
Definition at line 68 of file footprint_integration_test.cpp.
Referenced by anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::run_and_parse_footprint().
run_pin()
int anonymous_namespace{footprint_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 33 of file footprint_integration_test.cpp.
References a, env(), pin_root(), and PinCCTLib::status.
Referenced by anonymous_namespace{footprint_integration_test.cpp}::FootprintIntegration::run_and_parse_footprint().
TEST_F() [1/3]
anonymous_namespace{footprint_integration_test.cpp}::TEST_F (FootprintIntegration , AVX32SweepFootprintExceedsSmall)
Definition at line 131 of file footprint_integration_test.cpp.
TEST_F() [2/3]
anonymous_namespace{footprint_integration_test.cpp}::TEST_F (FootprintIntegration , LargeFootprintExceedsSmall)
Definition at line 114 of file footprint_integration_test.cpp.
TEST_F() [3/3]
anonymous_namespace{footprint_integration_test.cpp}::TEST_F (FootprintIntegration , RunsCleanlyOnLs)
Definition at line 104 of file footprint_integration_test.cpp.