CCTLib: anonymous_namespace{ins_reuse_integration_test.cpp} Namespace Reference
anonymous_namespace{ins_reuse_integration_test.cpp} Namespace Reference
Classes
class InsReuseIntegration
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
std::string find_newest (const std::string &dir, const std::string &prefix)
std::string read_file (const std::string &path)
void cleanup (const std::string &dir, const std::string &prefix)
std::vector< double > parse_histogram (const std::string &content)
TEST_F (InsReuseIntegration, RunsCleanlyOnLs)
TEST_F (InsReuseIntegration, TightLoopFillsLowBins)
TEST_F (InsReuseIntegration, SimdLoopFillsLowBins)
Function Documentation
cctlib_root()
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::cctlib_root ()
Definition at line 26 of file ins_reuse_integration_test.cpp.
References env().
Referenced by anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::SetUp().
cleanup()
void anonymous_namespace{ins_reuse_integration_test.cpp}::cleanup (const std::string & dir, const std::string & prefix)
Definition at line 67 of file ins_reuse_integration_test.cpp.
Referenced by anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::run_and_parse().
env()
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::env (const char * n)
Definition at line 25 of file ins_reuse_integration_test.cpp.
Referenced by cctlib_root(), pin_root(), and run_pin().
find_newest()
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::find_newest (const std::string & dir, const std::string & prefix)
Definition at line 54 of file ins_reuse_integration_test.cpp.
References buf.
Referenced by anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::run_and_parse().
parse_histogram()
std::vector<double> anonymous_namespace{ins_reuse_integration_test.cpp}::parse_histogram (const std::string & content)
Definition at line 74 of file ins_reuse_integration_test.cpp.
Referenced by anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::run_and_parse().
pin_root()
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::pin_root ()
Definition at line 27 of file ins_reuse_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::SetUp().
read_file()
std::string anonymous_namespace{ins_reuse_integration_test.cpp}::read_file (const std::string & path)
Definition at line 64 of file ins_reuse_integration_test.cpp.
Referenced by anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::run_and_parse().
run_pin()
int anonymous_namespace{ins_reuse_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 29 of file ins_reuse_integration_test.cpp.
References a, env(), pin_root(), and PinCCTLib::status.
Referenced by anonymous_namespace{ins_reuse_integration_test.cpp}::InsReuseIntegration::run_and_parse().
TEST_F() [1/3]
anonymous_namespace{ins_reuse_integration_test.cpp}::TEST_F (InsReuseIntegration , RunsCleanlyOnLs)
Definition at line 115 of file ins_reuse_integration_test.cpp.
References h().
TEST_F() [2/3]
anonymous_namespace{ins_reuse_integration_test.cpp}::TEST_F (InsReuseIntegration , SimdLoopFillsLowBins)
Definition at line 149 of file ins_reuse_integration_test.cpp.
References h().
TEST_F() [3/3]
anonymous_namespace{ins_reuse_integration_test.cpp}::TEST_F (InsReuseIntegration , TightLoopFillsLowBins)
Definition at line 130 of file ins_reuse_integration_test.cpp.
References h().