CCTLib: anonymous_namespace{redspy_integration_test.cpp} Namespace Reference
anonymous_namespace{redspy_integration_test.cpp} Namespace Reference
Classes
class RedspyIntegration
struct RedspyIsaVictim
class RedspyIsa
Functions
std::string env (const char *name)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
std::string find_newest (const std::string &dir, const std::string &prefix)
std::string read_file (const std::string &path)
void cleanup (const std::string &dir, const std::string &prefix)
double parse_first_redundant_pct (const std::string &content)
TEST_F (RedspyIntegration, RunsCleanlyOnLs)
TEST_F (RedspyIntegration, TruePositiveHigherThanTrueNegative)
TEST_F (RedspyIntegration, MultiSizeTruePositiveExceedsTN)
TEST_F (RedspyIntegration, TPReportAttributesToStore8)
TEST_P (RedspyIsa, ExceedsBaseline)
INSTANTIATE_TEST_SUITE_P (IsaBreadth, RedspyIsa, ::testing::Values(RedspyIsaVictim{"redspy_sse16_tp", 2.0}, RedspyIsaVictim{"redspy_avx32_tp", 2.0}, RedspyIsaVictim{"redspy_immediate_tp", 1.0}, RedspyIsaVictim{"redspy_partial_qword_then_byte_tp", 0.3}, RedspyIsaVictim{"redspy_zero_fill_tp", 2.0}, RedspyIsaVictim{"redspy_scalar_sse_tp", 1.0}, RedspyIsaVictim{"redspy_cross_page_tp", 0.5}), [](const testing::TestParamInfo< RedspyIsaVictim > &info) { return info.param.name;})
Function Documentation
cctlib_root()
std::string anonymous_namespace{redspy_integration_test.cpp}::cctlib_root ()
Definition at line 33 of file redspy_integration_test.cpp.
References env().
Referenced by anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::SetUp().
cleanup()
void anonymous_namespace{redspy_integration_test.cpp}::cleanup (const std::string & dir, const std::string & prefix)
Definition at line 75 of file redspy_integration_test.cpp.
Referenced by anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::run_and_parse_pct(), and TEST_F().
env()
std::string anonymous_namespace{redspy_integration_test.cpp}::env (const char * name)
Definition at line 32 of file redspy_integration_test.cpp.
Referenced by cctlib_root(), pin_root(), and run_pin().
find_newest()
std::string anonymous_namespace{redspy_integration_test.cpp}::find_newest (const std::string & dir, const std::string & prefix)
Definition at line 62 of file redspy_integration_test.cpp.
References buf.
Referenced by anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::run_and_parse_pct(), and TEST_F().
INSTANTIATE_TEST_SUITE_P()
anonymous_namespace{redspy_integration_test.cpp}::INSTANTIATE_TEST_SUITE_P (IsaBreadth , RedspyIsa , ::testing::Values(RedspyIsaVictim{"redspy_sse16_tp", 2.0}, RedspyIsaVictim{"redspy_avx32_tp", 2.0}, RedspyIsaVictim{"redspy_immediate_tp", 1.0}, RedspyIsaVictim{"redspy_partial_qword_then_byte_tp", 0.3}, RedspyIsaVictim{"redspy_zero_fill_tp", 2.0}, RedspyIsaVictim{"redspy_scalar_sse_tp", 1.0}, RedspyIsaVictim{"redspy_cross_page_tp", 0.5}) , [] (const testing::TestParamInfo< RedspyIsaVictim > &info) { return info.param.name;})
parse_first_redundant_pct()
double anonymous_namespace{redspy_integration_test.cpp}::parse_first_redundant_pct (const std::string & content)
Definition at line 81 of file redspy_integration_test.cpp.
Referenced by anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::run_and_parse_pct().
pin_root()
std::string anonymous_namespace{redspy_integration_test.cpp}::pin_root ()
Definition at line 34 of file redspy_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::SetUp().
read_file()
std::string anonymous_namespace{redspy_integration_test.cpp}::read_file (const std::string & path)
Definition at line 72 of file redspy_integration_test.cpp.
Referenced by anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::run_and_parse_pct().
run_pin()
int anonymous_namespace{redspy_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 36 of file redspy_integration_test.cpp.
References a, env(), pin_root(), and PinCCTLib::status.
Referenced by anonymous_namespace{redspy_integration_test.cpp}::RedspyIntegration::run_and_parse_pct(), and TEST_F().
TEST_F() [1/4]
anonymous_namespace{redspy_integration_test.cpp}::TEST_F (RedspyIntegration , MultiSizeTruePositiveExceedsTN)
Definition at line 136 of file redspy_integration_test.cpp.
TEST_F() [2/4]
anonymous_namespace{redspy_integration_test.cpp}::TEST_F (RedspyIntegration , RunsCleanlyOnLs)
Definition at line 111 of file redspy_integration_test.cpp.
TEST_F() [3/4]
anonymous_namespace{redspy_integration_test.cpp}::TEST_F (RedspyIntegration , TPReportAttributesToStore8)
Definition at line 146 of file redspy_integration_test.cpp.
References buf, cleanup(), find_newest(), and run_pin().
TEST_F() [4/4]
anonymous_namespace{redspy_integration_test.cpp}::TEST_F (RedspyIntegration , TruePositiveHigherThanTrueNegative)
Definition at line 122 of file redspy_integration_test.cpp.
TEST_P()
anonymous_namespace{redspy_integration_test.cpp}::TEST_P (RedspyIsa , ExceedsBaseline)
Definition at line 175 of file redspy_integration_test.cpp.