CCTLib: anonymous_namespace{recursion_integration_test.cpp} Namespace Reference
anonymous_namespace{recursion_integration_test.cpp} Namespace Reference
Classes
struct VictimSpec
class RecursionShape
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin_capture (const std::string &tool, const std::vector< std::string > &toolArgs, const std::string &victim, std::string *stderrOut)
TEST_P (RecursionShape, CctShapeAssertionsPass)
INSTANTIATE_TEST_SUITE_P (Victims, RecursionShape, ::testing::ValuesIn(kVictims), [](const testing::TestParamInfo< RecursionShape::ParamType > &info) { return std::string(info.param.name);})
Variables
const VictimSpec kVictims []
Function Documentation
cctlib_root()
std::string anonymous_namespace{recursion_integration_test.cpp}::cctlib_root ()
Definition at line 39 of file recursion_integration_test.cpp.
References env().
Referenced by anonymous_namespace{recursion_integration_test.cpp}::RecursionShape::SetUp().
env()
std::string anonymous_namespace{recursion_integration_test.cpp}::env (const char * n)
Definition at line 38 of file recursion_integration_test.cpp.
Referenced by cctlib_root(), and pin_root().
INSTANTIATE_TEST_SUITE_P()
anonymous_namespace{recursion_integration_test.cpp}::INSTANTIATE_TEST_SUITE_P (Victims , RecursionShape , ::testing::ValuesIn(kVictims) , [] (const testing::TestParamInfo< RecursionShape::ParamType > &info) { return std::string(info.param.name);})
pin_root()
std::string anonymous_namespace{recursion_integration_test.cpp}::pin_root ()
Definition at line 43 of file recursion_integration_test.cpp.
References env().
Referenced by run_pin_capture(), and anonymous_namespace{recursion_integration_test.cpp}::RecursionShape::SetUp().
run_pin_capture()
int anonymous_namespace{recursion_integration_test.cpp}::run_pin_capture (const std::string & tool, const std::vector< std::string > & toolArgs, const std::string & victim, std::string * stderrOut)
Definition at line 49 of file recursion_integration_test.cpp.
References a, buf, pin_root(), and PinCCTLib::status.
Referenced by TEST_P().
TEST_P()
anonymous_namespace{recursion_integration_test.cpp}::TEST_P (RecursionShape , CctShapeAssertionsPass)
Definition at line 120 of file recursion_integration_test.cpp.
References run_pin_capture().
Variable Documentation
kVictims
const VictimSpec anonymous_namespace{recursion_integration_test.cpp}::kVictims[]
Initial value:
= {
    { "rec_fib_deep"              },
    { "rec_ackermann"             },
    { "rec_multi_direct"          },
    { "rec_indirect_only"         },
    { "rec_mixed_direct_indirect" },
    { "rec_stripped"              },
    { "rec_exception"             },
    { "rec_baseline_nonrec"       },
}
Definition at line 99 of file recursion_integration_test.cpp.