CCTLib: anonymous_namespace{cctlib_integration_test.cpp} Namespace Reference
anonymous_namespace{cctlib_integration_test.cpp} Namespace Reference
Classes
class CCTLibIntegration
Functions
std::string env (const char *name)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
std::string find_newest (const std::string &dir, const std::string &prefix)
std::string read_file (const std::string &path)
void cleanup (const std::string &dir, const std::string &prefix)
TEST_F (CCTLibIntegration, CctClientRunsCleanly)
TEST_F (CCTLibIntegration, CctClientMemOnlyRunsCleanly)
TEST_F (CCTLibIntegration, CctDataCentricClientRunsCleanly)
TEST_F (CCTLibIntegration, CctDataCentricClientTreeBasedRunsCleanly)
Function Documentation
cctlib_root()
std::string anonymous_namespace{cctlib_integration_test.cpp}::cctlib_root ()
Definition at line 40 of file cctlib_integration_test.cpp.
References env().
Referenced by anonymous_namespace{cctlib_integration_test.cpp}::CCTLibIntegration::SetUp().
cleanup()
void anonymous_namespace{cctlib_integration_test.cpp}::cleanup (const std::string & dir, const std::string & prefix)
Definition at line 108 of file cctlib_integration_test.cpp.
Referenced by TEST_F().
env()
std::string anonymous_namespace{cctlib_integration_test.cpp}::env (const char * name)
Definition at line 32 of file cctlib_integration_test.cpp.
Referenced by cctlib_root(), pin_root(), and run_pin().
find_newest()
std::string anonymous_namespace{cctlib_integration_test.cpp}::find_newest (const std::string & dir, const std::string & prefix)
Definition at line 88 of file cctlib_integration_test.cpp.
References buf.
Referenced by TEST_F().
pin_root()
std::string anonymous_namespace{cctlib_integration_test.cpp}::pin_root ()
Definition at line 47 of file cctlib_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{cctlib_integration_test.cpp}::CCTLibIntegration::SetUp().
read_file()
std::string anonymous_namespace{cctlib_integration_test.cpp}::read_file (const std::string & path)
Definition at line 100 of file cctlib_integration_test.cpp.
Referenced by TEST_F().
run_pin()
int anonymous_namespace{cctlib_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 55 of file cctlib_integration_test.cpp.
References a, env(), pin_root(), and PinCCTLib::status.
Referenced by TEST_F().
TEST_F() [1/4]
anonymous_namespace{cctlib_integration_test.cpp}::TEST_F (CCTLibIntegration , CctClientMemOnlyRunsCleanly)
Definition at line 147 of file cctlib_integration_test.cpp.
References cleanup(), find_newest(), read_file(), and run_pin().
TEST_F() [2/4]
anonymous_namespace{cctlib_integration_test.cpp}::TEST_F (CCTLibIntegration , CctClientRunsCleanly)
Definition at line 131 of file cctlib_integration_test.cpp.
References cleanup(), find_newest(), read_file(), and run_pin().
TEST_F() [3/4]
anonymous_namespace{cctlib_integration_test.cpp}::TEST_F (CCTLibIntegration , CctDataCentricClientRunsCleanly)
Definition at line 160 of file cctlib_integration_test.cpp.
References cleanup(), find_newest(), and run_pin().
TEST_F() [4/4]
anonymous_namespace{cctlib_integration_test.cpp}::TEST_F (CCTLibIntegration , CctDataCentricClientTreeBasedRunsCleanly)
Definition at line 170 of file cctlib_integration_test.cpp.
References cleanup(), find_newest(), and run_pin().