CCTLib: anonymous_namespace{rvn_integration_test.cpp} Namespace Reference
anonymous_namespace{rvn_integration_test.cpp} Namespace Reference
Classes
class RVNIntegration
Functions
std::string env (const char *n)
std::string cctlib_root ()
std::string pin_root ()
int run_pin (const std::string &tool, const std::vector< std::string > &args)
std::string find_newest (const std::string &dir, const std::string &prefix)
std::string read_file (const std::string &path)
void cleanup (const std::string &dir, const std::string &prefix)
double parse_redundancy (const std::string &content)
TEST_F (RVNIntegration, RunsCleanlyOnLs)
TEST_F (RVNIntegration, TruePositiveAtLeastAsRedundantAsTrueNegative)
TEST_F (RVNIntegration, RepeatedAddRunsCleanly)
Function Documentation
cctlib_root()
std::string anonymous_namespace{rvn_integration_test.cpp}::cctlib_root ()
Definition at line 34 of file rvn_integration_test.cpp.
References env().
Referenced by anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::SetUp().
cleanup()
void anonymous_namespace{rvn_integration_test.cpp}::cleanup (const std::string & dir, const std::string & prefix)
Definition at line 75 of file rvn_integration_test.cpp.
Referenced by anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::run_and_parse_red().
env()
std::string anonymous_namespace{rvn_integration_test.cpp}::env (const char * n)
Definition at line 33 of file rvn_integration_test.cpp.
Referenced by cctlib_root(), pin_root(), and run_pin().
find_newest()
std::string anonymous_namespace{rvn_integration_test.cpp}::find_newest (const std::string & dir, const std::string & prefix)
Definition at line 62 of file rvn_integration_test.cpp.
References buf.
Referenced by anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::run_and_parse_red().
parse_redundancy()
double anonymous_namespace{rvn_integration_test.cpp}::parse_redundancy (const std::string & content)
Definition at line 80 of file rvn_integration_test.cpp.
Referenced by anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::run_and_parse_red().
pin_root()
std::string anonymous_namespace{rvn_integration_test.cpp}::pin_root ()
Definition at line 35 of file rvn_integration_test.cpp.
References env().
Referenced by run_pin(), and anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::SetUp().
read_file()
std::string anonymous_namespace{rvn_integration_test.cpp}::read_file (const std::string & path)
Definition at line 72 of file rvn_integration_test.cpp.
Referenced by anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::run_and_parse_red().
run_pin()
int anonymous_namespace{rvn_integration_test.cpp}::run_pin (const std::string & tool, const std::vector< std::string > & args)
Definition at line 37 of file rvn_integration_test.cpp.
References a, env(), pin_root(), and PinCCTLib::status.
Referenced by anonymous_namespace{rvn_integration_test.cpp}::RVNIntegration::run_and_parse_red().
TEST_F() [1/3]
anonymous_namespace{rvn_integration_test.cpp}::TEST_F (RVNIntegration , RepeatedAddRunsCleanly)
Definition at line 135 of file rvn_integration_test.cpp.
TEST_F() [2/3]
anonymous_namespace{rvn_integration_test.cpp}::TEST_F (RVNIntegration , RunsCleanlyOnLs)
Definition at line 107 of file rvn_integration_test.cpp.
TEST_F() [3/3]
anonymous_namespace{rvn_integration_test.cpp}::TEST_F (RVNIntegration , TruePositiveAtLeastAsRedundantAsTrueNegative)
Definition at line 122 of file rvn_integration_test.cpp.