CCTLib: anonymous_namespace{splay_deserialize_test.cpp} Namespace Reference
anonymous_namespace{splay_deserialize_test.cpp} Namespace Reference
Classes
struct TraceSplay
struct Diagnosis
class SplayDeserialize
Functions
TraceSplay * splay (TraceSplay *root, uintptr_t key)
void insert (TraceSplay **rootp, uintptr_t key, int value, bool apply_fix)
void collect_keys (TraceSplay *root, std::set< uintptr_t > &out)
bool splay_finds (TraceSplay **rootp, uintptr_t key)
Diagnosis run (bool apply_fix, const std::vector< uintptr_t > &seq)
TEST_P (SplayDeserialize, FixedIsWellFormed)
TEST_P (SplayDeserialize, BuggyLosesKeys)
INSTANTIATE_TEST_SUITE_P (Scenarios, SplayDeserialize, ::testing::Values(std::vector< uintptr_t >{100, 200, 300, 400, 500, 600, 700, 800}, std::vector< uintptr_t >{800, 700, 600, 500, 400, 300, 200, 100}, std::vector< uintptr_t >{500, 100, 900, 300, 700, 200, 800, 400, 600}))
Function Documentation
collect_keys()
void anonymous_namespace{splay_deserialize_test.cpp}::collect_keys (TraceSplay * root, std::set< uintptr_t > & out)
Definition at line 58 of file splay_deserialize_test.cpp.
References collect_keys(), anonymous_namespace{splay_deserialize_test.cpp}::TraceSplay::key, anonymous_namespace{splay_deserialize_test.cpp}::TraceSplay::left, and anonymous_namespace{splay_deserialize_test.cpp}::TraceSplay::right.
insert()
void anonymous_namespace{splay_deserialize_test.cpp}::insert (TraceSplay ** rootp, uintptr_t key, int value, bool apply_fix)
Definition at line 36 of file splay_deserialize_test.cpp.
References anonymous_namespace{splay_deserialize_test.cpp}::TraceSplay::left, anonymous_namespace{splay_deserialize_test.cpp}::TraceSplay::right, splay(), and value.
INSTANTIATE_TEST_SUITE_P()
anonymous_namespace{splay_deserialize_test.cpp}::INSTANTIATE_TEST_SUITE_P (Scenarios , SplayDeserialize , ::testing::Values(std::vector< uintptr_t >{100, 200, 300, 400, 500, 600, 700, 800}, std::vector< uintptr_t >{800, 700, 600, 500, 400, 300, 200, 100}, std::vector< uintptr_t >{500, 100, 900, 300, 700, 200, 800, 400, 600}))
run()
Diagnosis anonymous_namespace{splay_deserialize_test.cpp}::run (bool apply_fix, const std::vector< uintptr_t > & seq)
Definition at line 76 of file splay_deserialize_test.cpp.
References collect_keys(), insert(), anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis::missing_reachable, anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis::missing_splay, and splay_finds().
Referenced by TEST_P().
splay()
TraceSplay* anonymous_namespace{splay_deserialize_test.cpp}::splay (TraceSplay * root, uintptr_t key)
Definition at line 29 of file splay_deserialize_test.cpp.
References REGULAR_SPLAY_TREE.
splay_finds()
bool anonymous_namespace{splay_deserialize_test.cpp}::splay_finds (TraceSplay ** rootp, uintptr_t key)
Definition at line 65 of file splay_deserialize_test.cpp.
References splay().
TEST_P() [1/2]
anonymous_namespace{splay_deserialize_test.cpp}::TEST_P (SplayDeserialize , BuggyLosesKeys)
Definition at line 101 of file splay_deserialize_test.cpp.
References anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis::missing_reachable, anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis::missing_splay, and run().
TEST_P() [2/2]
anonymous_namespace{splay_deserialize_test.cpp}::TEST_P (SplayDeserialize , FixedIsWellFormed)
Definition at line 95 of file splay_deserialize_test.cpp.
References anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis::missing_reachable, anonymous_namespace{splay_deserialize_test.cpp}::Diagnosis::missing_splay, and run().