CCTLib: anonymous_namespace{rbtree_test.cpp} Namespace Reference
anonymous_namespace{rbtree_test.cpp} Namespace Reference
Classes
class NodeArena
Typedefs
using KV = TreeNode< uint64_t, uint32_t, uint64_t >
using Tree = RBTree< uint64_t, uint32_t, uint64_t >
Functions
TEST (RBTree, EmptyIsValid)
TEST (RBTree, InsertOne)
TEST (RBTree, InsertAscending)
TEST (RBTree, InsertDescending)
TEST (RBTree, InsertPseudoRandomLargeN)
TEST (RBTree, SumMatchesLinearScan)
TEST (RBTree, DeleteViaFindMaintainsInvariants)
TEST (RBTree, InsertDeleteAllYieldsValidEmpty)
Typedef Documentation
KV
using anonymous_namespace{rbtree_test.cpp}::KV = typedef TreeNode<uint64_t, uint32_t, uint64_t>
Definition at line 28 of file rbtree_test.cpp.
Tree
using anonymous_namespace{rbtree_test.cpp}::Tree = typedef RBTree<uint64_t, uint32_t, uint64_t>
Definition at line 29 of file rbtree_test.cpp.
Function Documentation
TEST() [1/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , DeleteViaFindMaintainsInvariants)
Definition at line 151 of file rbtree_test.cpp.
References a, RBTree< K, V, S >::Delete(), RBTree< K, V, S >::FindSumGreaterEqual(), RBTree< K, V, S >::Insert(), RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), RBTree< K, V, S >::IsTreeCorrect(), TreeNode< K, V, S >::key, and N.
TEST() [2/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , EmptyIsValid)
Definition at line 47 of file rbtree_test.cpp.
References RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), and RBTree< K, V, S >::IsTreeCorrect().
TEST() [3/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , InsertAscending)
Definition at line 63 of file rbtree_test.cpp.
References a, RBTree< K, V, S >::Insert(), RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), and RBTree< K, V, S >::IsTreeCorrect().
TEST() [4/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , InsertDeleteAllYieldsValidEmpty)
Definition at line 182 of file rbtree_test.cpp.
References a, RBTree< K, V, S >::Delete(), RBTree< K, V, S >::FindSumGreaterEqual(), RBTree< K, V, S >::Insert(), RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), and RBTree< K, V, S >::IsTreeCorrect().
TEST() [5/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , InsertDescending)
Definition at line 74 of file rbtree_test.cpp.
References a, RBTree< K, V, S >::Insert(), RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), and RBTree< K, V, S >::IsTreeCorrect().
TEST() [6/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , InsertOne)
Definition at line 54 of file rbtree_test.cpp.
References a, RBTree< K, V, S >::Insert(), RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), and RBTree< K, V, S >::IsTreeCorrect().
TEST() [7/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , InsertPseudoRandomLargeN)
Definition at line 85 of file rbtree_test.cpp.
References a, RBTree< K, V, S >::Insert(), RBTree< K, V, S >::IsBST(), RBTree< K, V, S >::IsSumCorrect(), and RBTree< K, V, S >::IsTreeCorrect().
TEST() [8/8]
anonymous_namespace{rbtree_test.cpp}::TEST (RBTree , SumMatchesLinearScan)
Definition at line 102 of file rbtree_test.cpp.
References a, data, RBTree< K, V, S >::FindSumGreaterEqual(), and RBTree< K, V, S >::Insert().