CCTLib: src/pin_isa_compat.H File Reference
pin_isa_compat.H File Reference
#include "pin.H"
#include "regvalue_utils.h"
Typedefs
using PIN_REGISTER = PINTOOL_REGISTER
Functions
static BOOL REG_is_in_X87 (REG reg)
static BOOL INS_IsIndirectBranchOrCall (INS ins)
static BOOL INS_IsMaskedJump (INS ins)
static USIZE INS_MemoryReadSize (INS ins)
static USIZE INS_MemoryWriteSize (INS ins)
Typedef Documentation
PIN_REGISTER
using PIN_REGISTER = PINTOOL_REGISTER
Definition at line 38 of file pin_isa_compat.H.
Function Documentation
INS_IsIndirectBranchOrCall()
static BOOL INS_IsIndirectBranchOrCall (INS ins) inline static
Definition at line 52 of file pin_isa_compat.H.
INS_IsMaskedJump()
static BOOL INS_IsMaskedJump (INS ins) inline static
Definition at line 63 of file pin_isa_compat.H.
Referenced by INS_IsIgnorable(), and IsIgnorableIns().
INS_MemoryReadSize()
static USIZE INS_MemoryReadSize (INS ins) inline static
Definition at line 88 of file pin_isa_compat.H.
Referenced by InstrumentTrace().
INS_MemoryWriteSize()
static USIZE INS_MemoryWriteSize (INS ins) inline static
Definition at line 98 of file pin_isa_compat.H.
Referenced by InstrumentTrace().
REG_is_in_X87()
static BOOL REG_is_in_X87 (REG reg) inline static
Definition at line 42 of file pin_isa_compat.H.
Referenced by InstrumentGeneralReg().