CCTLib: tests/snippet.cpp File Reference
snippet.cpp File Reference
Functions
static void CopyRegionToShadowMemory (uint8_t *address, uint64_t length)
static VOID ImageLoad (IMG img, VOID *v)
Function Documentation
CopyRegionToShadowMemory()
static void CopyRegionToShadowMemory (uint8_t * address, uint64_t length) inline static
Definition at line 6 of file snippet.cpp.
References address, GetOrCreateShadowBaseAddress(), PAGE_OFFSET, and PAGE_SIZE.
Referenced by ImageLoad().
ImageLoad()
static VOID ImageLoad (IMG img, VOID * v) static
Definition at line 22 of file snippet.cpp.
References CopyRegionToShadowMemory().