CCTLib: tests/splay_deserialize_test.cpp File Reference
splay_deserialize_test.cpp File Reference
#include "splay-macros.h"
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <set>
#include <vector>
Classes
struct TraceSplay
Functions
static TraceSplay * splay (TraceSplay *root, uintptr_t key)
static void insert (TraceSplay **rootp, uintptr_t key, int value, bool apply_fix)
static void collect_keys (TraceSplay *root, std::set< uintptr_t > &out)
static bool splay_finds (TraceSplay **rootp, uintptr_t key)
static bool run_scenario (bool apply_fix, const char *label, const std::vector< uintptr_t > &insertion_order)
int main ()
Function Documentation
collect_keys()
static void collect_keys (TraceSplay * root, std::set< uintptr_t > & out) static
Definition at line 88 of file splay_deserialize_test.cpp.
References TraceSplay::key, TraceSplay::left, and TraceSplay::right.
Referenced by anonymous_namespace{splay_deserialize_test.cpp}::collect_keys(), anonymous_namespace{splay_deserialize_test.cpp}::run(), and run_scenario().
insert()
static void insert (TraceSplay ** rootp, uintptr_t key, int value, bool apply_fix) static
Definition at line 63 of file splay_deserialize_test.cpp.
References TraceSplay::left, TraceSplay::right, splay(), and value.
Referenced by anonymous_namespace{splay_deserialize_test.cpp}::run(), and run_scenario().
main()
int main ()
Definition at line 142 of file splay_deserialize_test.cpp.
References mix(), and run_scenario().
run_scenario()
static bool run_scenario (bool apply_fix, const char * label, const std::vector< uintptr_t > & insertion_order) static
Definition at line 105 of file splay_deserialize_test.cpp.
References collect_keys(), insert(), and splay_finds().
Referenced by main().
splay()
static TraceSplay* splay (TraceSplay * root, uintptr_t key) static
Definition at line 53 of file splay_deserialize_test.cpp.
References REGULAR_SPLAY_TREE.
Referenced by PinCCTLib::DeserializeCCTNode(), anonymous_namespace{splay_deserialize_test.cpp}::insert(), insert(), PinCCTLib::InstrumentTraceEntry(), anonymous_namespace{splay_deserialize_test.cpp}::splay_finds(), and splay_finds().
splay_finds()
static bool splay_finds (TraceSplay ** rootp, uintptr_t key) static
Definition at line 98 of file splay_deserialize_test.cpp.
References splay().
Referenced by anonymous_namespace{splay_deserialize_test.cpp}::run(), and run_scenario().