CCTLib: UnrolledConjunction< start, end, incr > Struct Template Reference
UnrolledConjunction< start, end, incr > Struct Template Reference
Public Member Functions
UnrolledConjunction (addr, redmap)
Static Public Member Functions
static bool Body (const function< bool(const int)> &func)
static __attribute__ ((always_inline)) bool Body(const function< bool(const int)> &func)
static __attribute__ ((always_inline)) bool BodyContextCheck(ContextHandle_t *__restrict__ prevIP)
static __attribute__ ((always_inline)) bool Body(const function< bool(const int)> &func)
static __attribute__ ((always_inline)) bool Body(const function< bool(const int)> &func)
static __attribute__ ((always_inline)) bool BodyContextCheck(ContextHandle_t *__restrict__ prevIP)
static __attribute__ ((always_inline)) bool Body(const function< bool(const int)> &func)
static __attribute__ ((always_inline)) bool BodyContextCheck(ContextHandle_t *__restrict__ prevIP)
static __attribute__ ((always_inline)) uint32_t BodyIsZero(uint8_t *addr)
static __attribute__ ((always_inline)) uint32_t BodyByteMap(uint8_t *addr)
static __attribute__ ((always_inline)) bool Body(const function< bool(const int)> &func)
static __attribute__ ((always_inline)) bool BodyContextCheck(ContextHandle_t *__restrict__ prevIP)
static __attribute__ ((always_inline)) uint32_t BodyIsZero(uint8_t *addr)
static __attribute__ ((always_inline)) void BodyByteMap(uint8_t *addr
static __attribute__ ((always_inline)) void BodyByteMapApprox(uint8_t *addr
Public Attributes
static uint8_t redmap [32]
Detailed Description
template<int start, int end, int incr>
struct UnrolledConjunction< start, end, incr >
Definition at line 108 of file footprint_client.cpp.
Constructor & Destructor Documentation
UnrolledConjunction()
template<int start, int end, int incr> UnrolledConjunction< start, end, incr >::UnrolledConjunction (addr , redmap)
Member Function Documentation
__attribute__() [1/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 628 of file loadspy_client.cpp.
References UnrolledConjunction< start, end, incr >::Body().
__attribute__() [2/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 134 of file redspy_client.cpp.
References UnrolledConjunction< start, end, incr >::Body().
__attribute__() [3/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 1661 of file redspy_temporal_client.cpp.
References UnrolledConjunction< start, end, incr >::Body().
__attribute__() [4/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 745 of file zerospy_client.cpp.
References UnrolledConjunction< start, end, incr >::Body().
__attribute__() [5/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 710 of file zerospy_spatial_client.cpp.
References UnrolledConjunction< start, end, incr >::Body().
__attribute__() [6/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 631 of file loadspy_client.cpp.
__attribute__() [7/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 1664 of file redspy_temporal_client.cpp.
__attribute__() [8/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 748 of file zerospy_client.cpp.
__attribute__() [9/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 713 of file zerospy_spatial_client.cpp.
__attribute__() [10/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 754 of file zerospy_client.cpp.
__attribute__() [11/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 751 of file zerospy_client.cpp.
__attribute__() [12/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) inline static
Definition at line 716 of file zerospy_spatial_client.cpp.
__attribute__() [13/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) static
References DATA_STATE_NOT_ZERO, and DATA_STATE_ONLY_ZERO.
__attribute__() [14/14]
template<int start, int end, int incr> static UnrolledConjunction< start, end, incr >::__attribute__ ((always_inline)) static
References DATA_STATE_NOT_ZERO, and DATA_STATE_ONLY_ZERO.
Body()
template<int start, int end, int incr> static bool UnrolledConjunction< start, end, incr >::Body (const function< bool(const int)> & func) inline static
Definition at line 109 of file footprint_client.cpp.
Referenced by UnrolledConjunction< start, end, incr >::__attribute__().
Member Data Documentation
redmap
template<int start, int end, int incr> static uint8_t UnrolledConjunction< start, end, incr >::redmap
Initial value:
{
        redmap[start] = addr[start] == 0 ? DATA_STATE_ONLY_ZERO : DATA_STATE_NOT_ZERO
Definition at line 719 of file zerospy_spatial_client.cpp.
The documentation for this struct was generated from the following files:
clients/footprint_client.cpp
clients/zerospy_spatial_client.cpp
clients/loadspy_client.cpp
clients/redspy_client.cpp
clients/redspy_temporal_client.cpp
clients/zerospy_client.cpp