CCTLib: MemAnalysis< AccessLen > Struct Template Reference
MemAnalysis< AccessLen > Struct Template Reference
Static Public Member Functions
static VOID RecordNByteMemRead (void *addr, uint32_t opaqueHandle, ADDRINT insPtr, THREADID threadId)
static VOID RecordNByteMemWrite (void *addr, uint32_t opaqueHandle, ADDRINT insPtr, THREADID threadId)
Detailed Description
template<uint16_t AccessLen>
struct MemAnalysis< AccessLen >
Definition at line 260 of file footprint_client.cpp.
Member Function Documentation
RecordNByteMemRead()
template<uint16_t AccessLen> static VOID MemAnalysis< AccessLen >::RecordNByteMemRead (void * addr, uint32_t opaqueHandle, ADDRINT insPtr, THREADID threadId) inline static
Definition at line 261 of file footprint_client.cpp.
References UnrolledLoop< start, end, incr >::Body(), GetOrCreateShadowBaseAddress(), IsFwdDependence(), PinCCTLib::metric, PAGE_OFFSET, PAGE_OFFSET_MASK, RecordOneByteMemRead(), PinCCTLib::status, and UpdateFootPrint().
RecordNByteMemWrite()
template<uint16_t AccessLen> static VOID MemAnalysis< AccessLen >::RecordNByteMemWrite (void * addr, uint32_t opaqueHandle, ADDRINT insPtr, THREADID threadId) inline static
Definition at line 293 of file footprint_client.cpp.
References UnrolledLoop< start, end, incr >::Body(), GetOrCreateShadowBaseAddress(), PAGE_OFFSET, PAGE_OFFSET_MASK, RecordOneByteMemWrite(), PinCCTLib::status, and UpdateFootPrint().
The documentation for this struct was generated from the following file:
clients/footprint_client.cpp