CCTLib: LoadSpyInstrument Struct Reference
LoadSpyInstrument Struct Reference
Public Member Functions
if (IsFloatInstructionAndOkToApproximate(INS_Address(ins)))
if (IsFloatInstructionAndOkToApproximate(INS_Address(ins)))
if (IsFloatInstructionAndOkToApproximate(INS_Address(ins)))
if (IsFloatInstructionAndOkToApproximate(INS_Address(ins)))
Static Public Member Functions
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterLoading(INS ins
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterLoading(INS ins
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterLoading(INS ins
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterLoading(INS ins
Public Attributes
static UINT32 memOp
static UINT32 uint32_t opaqueHandle
Detailed Description
Definition at line 882 of file loadspy_client.cpp.
Member Function Documentation
__attribute__() [1/4]
static LoadSpyInstrument::__attribute__ ((always_inline)) static
__attribute__() [2/4]
static LoadSpyInstrument::__attribute__ ((always_inline)) static
__attribute__() [3/4]
static LoadSpyInstrument::__attribute__ ((always_inline)) static
__attribute__() [4/4]
static LoadSpyInstrument::__attribute__ ((always_inline)) static
if() [1/4]
LoadSpyInstrument::if (IsFloatInstructionAndOkToApproximate(INS_Address(ins))) inline
Definition at line 886 of file loadspy_client.cpp.
References FloatOperandSize(), and HANDLE_CASE.
if() [2/4]
LoadSpyInstrument::if (IsFloatInstructionAndOkToApproximate(INS_Address(ins))) inline
Definition at line 664 of file zerospy_cachepage.cpp.
References FloatOperandSize(), and HANDLE_CASE.
if() [3/4]
LoadSpyInstrument::if (IsFloatInstructionAndOkToApproximate(INS_Address(ins))) inline
Definition at line 1125 of file zerospy_client.cpp.
References FloatOperandSize(), and HANDLE_CASE.
if() [4/4]
LoadSpyInstrument::if (IsFloatInstructionAndOkToApproximate(INS_Address(ins))) inline
Definition at line 893 of file zerospy_spatial_client.cpp.
References FloatOperandSize(), and HANDLE_CASE.
Member Data Documentation
memOp
static UINT32 LoadSpyInstrument::memOp
Definition at line 883 of file loadspy_client.cpp.
opaqueHandle
static UINT32 uint32_t LoadSpyInstrument::opaqueHandle
Initial value:
{
        UINT32 refSize = INS_MemoryOperandSize(ins, memOp)
Definition at line 883 of file loadspy_client.cpp.
The documentation for this struct was generated from the following files:
clients/loadspy_client.cpp
clients/zerospy_cachepage.cpp
clients/zerospy_client.cpp
clients/zerospy_spatial_client.cpp