CCTLib: UnrolledLoop< start, end, incr > Struct Template Reference
UnrolledLoop< start, end, incr > Struct Template Reference
Public Member Functions
UnrolledLoop (prevIP, handle, threadId)
if (conditional)
UnrolledLoop (addr, handle, threadId)
UnrolledLoop (prevIP, handle, threadId)
if (conditional)
UnrolledLoop (addr, handle, threadId)
Static Public Member Functions
static void Body (const function< void(const int)> &func)
static __attribute__ ((always_inline)) void Body(const function< void(const int)> &func)
static __attribute__ ((always_inline)) void BodySamePage(ContextHandle_t *__restrict__ prevIP
static __attribute__ ((always_inline)) void BodyStraddlePage(uint64_t addr
static __attribute__ ((always_inline)) void Body(const function< void(const int)> &func)
static __attribute__ ((always_inline)) void Body(const function< void(const int)> &func)
static __attribute__ ((always_inline)) void BodySamePage(ContextHandle_t *__restrict__ prevIP
static __attribute__ ((always_inline)) void BodyStraddlePage(uint64_t addr
Public Attributes
static const ContextHandle_t handle
static const ContextHandle_t THREADID threadId
ContextHandle_t * prevIP = &(get<1>(t)[PAGE_OFFSET(((uint64_t)addr + start))])
prevIP [0] = handle
Detailed Description
template<int start, int end, int incr>
struct UnrolledLoop< start, end, incr >
Definition at line 93 of file footprint_client.cpp.
Constructor & Destructor Documentation
UnrolledLoop() [1/4]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::UnrolledLoop (prevIP , handle , threadId)
UnrolledLoop() [2/4]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::UnrolledLoop (addr , handle , threadId)
UnrolledLoop() [3/4]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::UnrolledLoop (prevIP , handle , threadId)
UnrolledLoop() [4/4]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::UnrolledLoop (addr , handle , threadId)
Member Function Documentation
__attribute__() [1/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 586 of file loadspy_client.cpp.
References UnrolledLoop< start, end, incr >::Body().
__attribute__() [2/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 119 of file redspy_client.cpp.
References UnrolledLoop< start, end, incr >::Body().
__attribute__() [3/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) const & inline static
Definition at line 1620 of file redspy_temporal_client.cpp.
References UnrolledLoop< start, end, incr >::Body().
__attribute__() [4/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) static
References AddToApproximateRedTable(), AddToRedTable(), and MAKE_CONTEXT_PAIR.
__attribute__() [5/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) static
References AddToApproximateRedTable(), AddToRedTable(), and MAKE_CONTEXT_PAIR.
__attribute__() [6/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) static
References sm.
__attribute__() [7/7]
template<int start, int end, int incr> static UnrolledLoop< start, end, incr >::__attribute__ ((always_inline)) static
References PAGE_OFFSET, sm, and PinCCTLib::status.
Body()
template<int start, int end, int incr> static void UnrolledLoop< start, end, incr >::Body (const function< void(const int)> & func) inline static
Definition at line 94 of file footprint_client.cpp.
Referenced by UnrolledLoop< start, end, incr >::__attribute__(), RedSpyAnalysis< AccessLen, bufferOffset >::if(), MemAnalysis< AccessLen >::RecordNByteMemRead(), and MemAnalysis< AccessLen >::RecordNByteMemWrite().
if() [1/2]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::if (conditional) inline
Definition at line 606 of file loadspy_client.cpp.
References AddToApproximateRedTable(), AddToRedTable(), and MAKE_CONTEXT_PAIR.
if() [2/2]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::if (conditional) inline
Definition at line 1639 of file redspy_temporal_client.cpp.
References AddToApproximateRedTable(), AddToRedTable(), and MAKE_CONTEXT_PAIR.
Member Data Documentation
handle
template<int start, int end, int incr> static const ContextHandle_t UnrolledLoop< start, end, incr >::handle
Definition at line 590 of file loadspy_client.cpp.
prevIP [1/2]
template<int start, int end, int incr> ContextHandle_t * UnrolledLoop< start, end, incr >::prevIP = &(get<1>(t)[PAGE_OFFSET(((uint64_t)addr + start))])
Definition at line 604 of file loadspy_client.cpp.
prevIP [2/2]
template<int start, int end, int incr> UnrolledLoop< start, end, incr >::prevIP[0] = handle
Definition at line 614 of file loadspy_client.cpp.
threadId
template<int start, int end, int incr> static const ContextHandle_t THREADID UnrolledLoop< start, end, incr >::threadId
Initial value:
{
        if (conditional) {
            if (approx)
                AddToApproximateRedTable(MAKE_CONTEXT_PAIR(prevIP[start], handle), 1, threadId);
            else
                AddToRedTable(MAKE_CONTEXT_PAIR(prevIP[start], handle), 1, threadId);
        }
        prevIP[start] = handle
Definition at line 590 of file loadspy_client.cpp.
The documentation for this struct was generated from the following files:
clients/footprint_client.cpp
clients/loadspy_client.cpp
clients/redspy_temporal_client.cpp
clients/redspy_client.cpp