CCTLib: RedSpyInstrument< readBufferSlotIndex > Struct Template Reference
RedSpyInstrument< readBufferSlotIndex > Struct Template Reference
Public Member Functions
switch (refSize)
switch (refSize)
if (IsFloatInstruction(INS_Address(ins)))
Static Public Member Functions
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterWriting(INS ins
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterWriting(INS ins
static __attribute__ ((always_inline)) void InstrumentReadValueBeforeAndAfterWriting(INS ins
Public Attributes
static UINT32 memOp
static UINT32 bool hasFallThru
static UINT32 uint32_t opaqueHandle
Detailed Description
template<uint32_t readBufferSlotIndex>
struct RedSpyInstrument< readBufferSlotIndex >
Definition at line 365 of file cache_client.cpp.
Member Function Documentation
__attribute__() [1/3]
template<uint32_t readBufferSlotIndex> static RedSpyInstrument< readBufferSlotIndex >::__attribute__ ((always_inline)) static
__attribute__() [2/3]
template<uint32_t readBufferSlotIndex> static RedSpyInstrument< readBufferSlotIndex >::__attribute__ ((always_inline)) static
__attribute__() [3/3]
template<uint32_t readBufferSlotIndex> static RedSpyInstrument< readBufferSlotIndex >::__attribute__ ((always_inline)) static
if()
template<uint32_t readBufferSlotIndex> RedSpyInstrument< readBufferSlotIndex >::if (IsFloatInstruction(INS_Address(ins))) inline
Definition at line 1989 of file redspy_temporal_client.cpp.
References FloatOperandSize(), and HANDLE_APPROX_CASE.
switch() [1/2]
template<uint32_t readBufferSlotIndex> RedSpyInstrument< readBufferSlotIndex >::switch (refSize) inline
Definition at line 368 of file cache_client.cpp.
References HANDLE_CASE, and HANDLE_LARGE.
switch() [2/2]
template<uint32_t readBufferSlotIndex> RedSpyInstrument< readBufferSlotIndex >::switch (refSize) inline
Definition at line 455 of file redspy_client.cpp.
References CheckAfterLargeWrite(), HANDLE_CASE, and RecordValueBeforeLargeWrite().
Member Data Documentation
hasFallThru
template<uint32_t readBufferSlotIndex> UINT32 bool RedSpyInstrument< readBufferSlotIndex >::hasFallThru
Initial value:
{
        UINT32 refSize = INS_MemoryOperandSize(ins, memOp)
Definition at line 366 of file cache_client.cpp.
memOp
template<uint32_t readBufferSlotIndex> static UINT32 RedSpyInstrument< readBufferSlotIndex >::memOp
Definition at line 366 of file cache_client.cpp.
opaqueHandle
template<uint32_t readBufferSlotIndex> static UINT32 uint32_t RedSpyInstrument< readBufferSlotIndex >::opaqueHandle
Initial value:
{
        UINT32 refSize = INS_MemoryOperandSize(ins, memOp)
Definition at line 453 of file redspy_client.cpp.
The documentation for this struct was generated from the following files:
clients/cache_client.cpp
clients/redspy_client.cpp
clients/redspy_temporal_client.cpp