CCTLib: AssertionRecorder Struct Reference
AssertionRecorder Struct Reference
Public Member Functions
template<typename A , typename B >
void expectLE (A obs, B lim, const char *what)
template<typename A , typename B >
void expectGE (A obs, B lim, const char *what)
template<typename A , typename B , typename C >
void expectInRange (A obs, B lo, C hi, const char *what)
template<typename A , typename B >
void expectEQ (A obs, B want, const char *what)
void expectTrue (bool b, const char *what)
void expectNoSentinels (const CctInventory &inv)
Public Attributes
vector< string > failures
const char * checkName
Detailed Description
Definition at line 451 of file cct_shape_check.cpp.
Member Function Documentation
expectEQ()
template<typename A , typename B > void AssertionRecorder::expectEQ (A obs, B want, const char * what) inline
Definition at line 483 of file cct_shape_check.cpp.
Referenced by check_exc_deep_unwind(), check_rec_ackermann(), check_rec_exception(), check_rec_fib_deep(), check_rec_indirect_only(), check_rec_mixed_direct_indirect(), and check_rec_multi_direct().
expectGE()
template<typename A , typename B > void AssertionRecorder::expectGE (A obs, B lim, const char * what) inline
Definition at line 465 of file cct_shape_check.cpp.
Referenced by check_rec_baseline_nonrec().
expectInRange()
template<typename A , typename B , typename C > void AssertionRecorder::expectInRange (A obs, B lo, C hi, const char * what) inline
Definition at line 474 of file cct_shape_check.cpp.
expectLE()
template<typename A , typename B > void AssertionRecorder::expectLE (A obs, B lim, const char * what) inline
Definition at line 456 of file cct_shape_check.cpp.
Referenced by check_exc_ctor_throw(), and check_exc_recurse_trycatch().
expectNoSentinels()
void AssertionRecorder::expectNoSentinels (const CctInventory & inv) inline
Definition at line 498 of file cct_shape_check.cpp.
References CctInventory::sentinelCounts.
Referenced by check_exc_catch_and_resume(), check_exc_catchall(), check_exc_ctor_throw(), check_exc_deep_unwind(), check_exc_dtor_cleanup(), check_exc_none_tn(), check_exc_polymorphic(), check_exc_recurse_trycatch(), check_exc_rethrow(), check_exc_simple_throw(), check_exc_stress_loop(), check_exc_uncaught_tn(), check_rec_ackermann(), check_rec_baseline_nonrec(), check_rec_exception(), check_rec_fib_deep(), check_rec_indirect_only(), check_rec_mixed_direct_indirect(), check_rec_multi_direct(), check_rec_stripped(), check_sig_longjmp(), and check_sig_sigsegv_recover().
expectTrue()
void AssertionRecorder::expectTrue (bool b, const char * what) inline
Definition at line 491 of file cct_shape_check.cpp.
Referenced by check_exc_catch_and_resume(), check_exc_catchall(), check_exc_ctor_throw(), check_exc_deep_unwind(), check_exc_dtor_cleanup(), check_exc_none_tn(), check_exc_polymorphic(), check_exc_recurse_trycatch(), check_exc_rethrow(), check_exc_simple_throw(), check_exc_stress_loop(), check_exc_uncaught_tn(), check_rec_ackermann(), check_rec_exception(), check_rec_fib_deep(), check_rec_indirect_only(), check_rec_mixed_direct_indirect(), check_rec_multi_direct(), check_rec_stripped(), check_sig_longjmp(), check_sig_sigsegv_recover(), and expectMarkerAnchored().
Member Data Documentation
checkName
const char* AssertionRecorder::checkName
Definition at line 453 of file cct_shape_check.cpp.
Referenced by RunChecksAndExit().
failures
vector<string> AssertionRecorder::failures
Definition at line 452 of file cct_shape_check.cpp.
Referenced by RunChecksAndExit().
The documentation for this struct was generated from the following file:
clients/cct_shape_check.cpp