CCTLib: CctInventory Struct Reference
CctInventory Struct Reference
Public Member Functions
size_t chainCountForFn (const string &fn) const
bool hasChain (const vector< string > &expected) const
bool hasFn (const string &fn) const
bool anyChainContainsFn (const string &fn) const
bool everyChainToFnHasImmediateParent (const string &leafFn, const string &expectedParent) const
size_t maxCountInAnyChain (const string &fn) const
size_t subChainCountForFn (const string &fn) const
bool subHasFn (const string &fn) const
bool subAnyChainContainsFn (const string &fn) const
size_t subMaxCountInAnyChain (const string &fn) const
size_t subChainsContainingFn (const string &fn) const
bool everySubChainToFnHasImmediateParent (const string &leafFn, const string &expectedParent) const
bool noAncestorOfFnIsInSet (const string &fn, const set< string > &badAncestors) const
Public Attributes
map< FnChain, uint64_t > chains
map< string, set< FnChain > > byLeafFn
map< string, uint64_t > hitsByLeafFn
map< string, size_t > sentinelCounts
map< string, size_t > softSentinelCounts
size_t maxDepthObserved = 0
size_t totalDistinctHandles = 0
map< FnChain, uint64_t > subChains
map< string, set< FnChain > > subByLeafFn
size_t subMaxDepthObserved = 0
Detailed Description
Definition at line 165 of file cct_shape_check.cpp.
Member Function Documentation
anyChainContainsFn()
bool CctInventory::anyChainContainsFn (const string & fn) const inline
Definition at line 200 of file cct_shape_check.cpp.
Referenced by check_exc_ctor_throw().
chainCountForFn()
size_t CctInventory::chainCountForFn (const string & fn) const inline
Definition at line 190 of file cct_shape_check.cpp.
everyChainToFnHasImmediateParent()
bool CctInventory::everyChainToFnHasImmediateParent (const string & leafFn, const string & expectedParent) const inline
Definition at line 211 of file cct_shape_check.cpp.
Referenced by check_exc_catch_and_resume(), check_exc_deep_unwind(), check_exc_polymorphic(), check_exc_simple_throw(), check_exc_stress_loop(), check_exc_uncaught_tn(), check_sig_longjmp(), and expectMarkerAnchored().
everySubChainToFnHasImmediateParent()
bool CctInventory::everySubChainToFnHasImmediateParent (const string & leafFn, const string & expectedParent) const inline
Definition at line 284 of file cct_shape_check.cpp.
Referenced by check_rec_ackermann(), check_rec_exception(), check_rec_fib_deep(), and check_rec_multi_direct().
hasChain()
bool CctInventory::hasChain (const vector< string > & expected) const inline
Definition at line 194 of file cct_shape_check.cpp.
hasFn()
bool CctInventory::hasFn (const string & fn) const inline
Definition at line 197 of file cct_shape_check.cpp.
Referenced by check_exc_catchall(), check_exc_deep_unwind(), check_exc_dtor_cleanup(), check_exc_recurse_trycatch(), check_exc_rethrow(), check_exc_uncaught_tn(), check_rec_stripped(), check_sig_longjmp(), check_sig_sigsegv_recover(), and expectMarkerAnchored().
maxCountInAnyChain()
size_t CctInventory::maxCountInAnyChain (const string & fn) const inline
Definition at line 226 of file cct_shape_check.cpp.
Referenced by check_exc_ctor_throw(), check_exc_deep_unwind(), and check_exc_recurse_trycatch().
noAncestorOfFnIsInSet()
bool CctInventory::noAncestorOfFnIsInSet (const string & fn, const set< string > & badAncestors) const inline
Definition at line 303 of file cct_shape_check.cpp.
Referenced by expectMarkerAnchored().
subAnyChainContainsFn()
bool CctInventory::subAnyChainContainsFn (const string & fn) const inline
Definition at line 248 of file cct_shape_check.cpp.
Referenced by check_exc_catchall(), check_exc_dtor_cleanup(), check_exc_none_tn(), check_exc_rethrow(), and check_sig_sigsegv_recover().
subChainCountForFn()
size_t CctInventory::subChainCountForFn (const string & fn) const inline
Definition at line 241 of file cct_shape_check.cpp.
Referenced by check_rec_ackermann(), check_rec_exception(), check_rec_fib_deep(), check_rec_indirect_only(), check_rec_mixed_direct_indirect(), and check_rec_multi_direct().
subChainsContainingFn()
size_t CctInventory::subChainsContainingFn (const string & fn) const inline
Definition at line 271 of file cct_shape_check.cpp.
subHasFn()
bool CctInventory::subHasFn (const string & fn) const inline
Definition at line 245 of file cct_shape_check.cpp.
Referenced by check_rec_ackermann(), check_rec_exception(), check_rec_fib_deep(), check_rec_indirect_only(), check_rec_mixed_direct_indirect(), and check_rec_multi_direct().
subMaxCountInAnyChain()
size_t CctInventory::subMaxCountInAnyChain (const string & fn) const inline
Definition at line 256 of file cct_shape_check.cpp.
Referenced by check_rec_ackermann(), check_rec_exception(), check_rec_fib_deep(), check_rec_indirect_only(), check_rec_mixed_direct_indirect(), and check_rec_multi_direct().
Member Data Documentation
byLeafFn
map<string, set<FnChain> > CctInventory::byLeafFn
Definition at line 169 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and RunChecksAndExit().
chains
map<FnChain, uint64_t> CctInventory::chains
Definition at line 167 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and RunChecksAndExit().
hitsByLeafFn
map<string, uint64_t> CctInventory::hitsByLeafFn
Definition at line 171 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and RunChecksAndExit().
maxDepthObserved
size_t CctInventory::maxDepthObserved = 0
Definition at line 176 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and RunChecksAndExit().
sentinelCounts
map<string, size_t> CctInventory::sentinelCounts
Definition at line 174 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and AssertionRecorder::expectNoSentinels().
softSentinelCounts
map<string, size_t> CctInventory::softSentinelCounts
Definition at line 175 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread().
subByLeafFn
map<string, set<FnChain> > CctInventory::subByLeafFn
Definition at line 187 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread().
subChains
map<FnChain, uint64_t> CctInventory::subChains
Definition at line 186 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and check_rec_baseline_nonrec().
subMaxDepthObserved
size_t CctInventory::subMaxDepthObserved = 0
Definition at line 188 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread().
totalDistinctHandles
size_t CctInventory::totalDistinctHandles = 0
Definition at line 177 of file cct_shape_check.cpp.
Referenced by BuildInventoryFromThread(), and RunChecksAndExit().
The documentation for this struct was generated from the following file:
clients/cct_shape_check.cpp