all:
	gcc -g test.c -o test
	gcc -g test2.c -o test2
	gcc -g test3.c -o test3
	gcc -g test4.c -o test4
	gcc -g test5.c -o test5
	gcc -g testArray.c -o testArray
	gcc -g test6.c -o test6 -lm
	gcc -g test8.c -o test8

clean:
	rm test test2 test3 test4 test5 testArray test6 test8
