all:
	gcc -std=c99 -O2 -fno-inline -g intraFunc.c -o intraFunc
	gcc -std=c99 -O2 -fno-inline -g interFunc.c -o interFunc
	gcc -std=c99 -O2 -fno-inline -g interFile.c -o interFile

clean:
	rm intraFunc interFunc interFile
